[DUNGEON] DSL Files in einer `jar` aus `game.jar` einlesen
Programmiermethoden/Dungeon pull request #1003
Opened 2023-09-04 16:32 UTC by Lena241

fixes #882 

- Bug in `TestDslFileLoader#emptyFileToString` behoben, der unter Windows die Slashes nicht richtig gesetzt hat

- eigenes Gradle-Target für die Erstellung eines Jars für das DSL-Dungeon hinzugefügt

2023-10-09 10:14 UTC, Lena241 commented
Entry-Points werden nicht gefunden, aber das Einlesen und Verarbeiten von Jar-Files aus der IDE , wie auch aus einer anderen Jar-Datei, funktioniert nun meines Erachtens. Um sicherzustellen, dass wirklich alles so funktioniert, wie es soll, muss vorher #1072 bearbeitet werden.

2023-10-23 13:42 UTC, AMatutat requested changes
Bitte alles rauswerfen was "nur zum testen" notwendig war (kopierter Starter, WizzardTest etc.).

2023-10-23 13:42 UTC, AMatutat commented on dungeon/src/graphconverter/TaskBuilder.java
vermutlich zum testen wichtig gewesen, aber hat so nix mit den PR zu tun.

2023-10-23 13:42 UTC, AMatutat commented on dungeon/src/starter/Starter.java
vermutlich zum testen wichtig gewesen, aber hat so nix mit den PR zu tun.

2023-10-23 13:42 UTC, AMatutat commented on dungeon/src/starter/WizardTaskSelector.java
vermutlich zum testen wichtig gewesen, aber hat so nix mit den PR zu tun.

2023-10-23 13:42 UTC, AMatutat commented on dsl/src/interpreter/DSLEntryPointFinder.java
@malt-r sein file

2023-10-23 14:10 UTC, AMatutat requested changes

2023-10-23 14:10 UTC, AMatutat commented on dungeon/src/dungeonFiles/DslFileLoader.java
> +    public static String fileToStringFromJar(Path path) {
javadoc

2023-10-23 14:10 UTC, AMatutat commented on dungeon/src/dungeonFiles/DslFileLoader.java
> +    public static String fileToString(Path path) {
javadoc

2023-10-23 14:48 UTC, AMatutat approved these changes
lgtm

damit ist das Ding endlich durch GJ :)

2023-10-23 14:50 UTC, merged