[GAME] Items aus Inventar per Tastendruck verwenden
Programmiermethoden/Dungeon pull request #1093
Opened 2023-10-24 16:05 UTC by Lena241

fixes #950

Die Items im Inventar können nun per Tastendruck benutzt werden. Dazu muss mit der Maus über das Item gehovert und die Taste 'E' gedrückt werden. 
*Hinweis*: Items, die in einem anderen Inventar sind (z.B. das der Schatztruhe), können nicht direkt benutzt werden und müssen erst in das Spielerinventar gepackt werden.

2023-10-24 19:48 UTC, AMatutat requested changes
Kleinkram

2023-10-24 19:48 UTC, AMatutat commented on game/src/contrib/hud/inventory/InventoryGUI.java
> +                                if (inHeroInventory && (character == 'e' || character == 'E')) {
Das sollte irgendwo stehen, wo man es konfigurieren kann. Keyboard config oderso

2023-10-24 19:48 UTC, AMatutat commented on game/src/contrib/hud/inventory/InventoryGUI.java
> +    public static boolean inHeroInventory = false;
Javadoc

2023-10-25 11:49 UTC, AMatutat commented on game/src/contrib/hud/inventory/InventoryGUI.java
> +                                if (inHeroInventory && (character == 'e' || character == 'E')) {
haben wir grade im meeting zusammen gemacht, bitte testen

2023-10-25 13:08 UTC, Lena241 commented on game/src/contrib/hud/inventory/InventoryGUI.java
> +                                if (inHeroInventory && (character == 'e' || character == 'E')) {
Läuft

2023-10-25 17:42 UTC, AMatutat approved these changes

2023-10-25 17:43 UTC, merged