[Puplication] add own paper
Programmiermethoden/Dungeon pull request #1224
Opened 2023-11-20 10:28 UTC by AMatutat

Fixes #745

Fügt das Verzeichnis `doc/publication` hinzu.
Fügt folgende Veröffentlichungen hinzu:
- StartPlay 2023: Paper (Präsentation ist identisch mit der DLK)
- DLK23: Präsentations-PDF
- UFF: Präsentations-PDF

Die D2G: Paper hat @AKirsch1 schon mal bei sich hochgeladen (zumindest habe ich da die Tage etwas gesehen).

Fügt eine eigene LICENSE.md (cc-by-sa 4.) hinzu und fügt einen Hinweis auf die wechselnde Lizenz im Top-Level Readme hinzu.

2023-11-20 10:32 UTC, AKirsch1 commented
> Die D2G: Paper hat @AKirsch1 schon mal bei sich hochgeladen

Ja, das Paper liegt schon im D2G-Repo.

2023-11-20 10:52 UTC, AMatutat commented
argh kommando zurück

> all of the licenses available at the root level of the repository

man muss halt auch mal lesen was da steht...

2023-11-27 16:01 UTC, cagix requested changes

2023-11-27 16:01 UTC, cagix commented on doc/publication/readme.md
> +Bitte beachten Sie unbedingt die [LICENSE-PAPER.md](../../LICENSE-PAPER.md)
```suggestion
Alle Dateien in diesem Ordner ([`doc/publication/`](.)) stehen abweichend von den restlichen Inhalten des Repositories unter der [CC BY-SA 4.0](../../LICENSE-PAPER.md) Lizenz.
```

2023-11-27 16:06 UTC, AMatutat commented on doc/publication/2023-09-28_startplay_learning -by-questing.pdf
gute Augen.
fixed.

2023-11-27 16:07 UTC, cagix commented on README.md
> +All files [in `doc/publication/`](doc/publication/) are licensed under [CC BY-SA 4.0](LICENSE-PAPER.md).
```suggestion
All files in [`doc/publication/`](doc/publication/) are licensed under [CC BY-SA 4.0](LICENSE-PAPER.md).
```

2023-11-27 16:09 UTC, cagix approved these changes
hmmm, nur drei sachen? hatten wir nicht noch mehr, gerade ende letzten jahres? (die d2g-sachen sind drüben im anderen repo.)

2023-11-27 16:13 UTC, AMatutat commented
> hmmm, nur drei sachen? hatten wir nicht noch mehr, gerade ende letzten jahres? (die d2g-sachen sind drüben im anderen repo.)

Oh ja stimmt, ich hab nur im 2022 repo geguckt, im 2021er müssten auch noch zwei Sachen liegen.  Ich guck mal

2023-11-27 16:24 UTC, AMatutat commented
@cagix so, das war aber das letzte für hier

2023-11-27 17:35 UTC, merged

2023-11-27 18:04 UTC, cagix approved these changes
ta