Upgrade Gradle, Java, Tools
Programmiermethoden/Dungeon pull request #1313
Opened 2023-12-19 00:49 UTC by fwatermann

closes #1010 
closes #1050

Hochziehen von Gradle, JDK, spotbugs, spotless, libGDX, Gson.

Gradle: 8.5
JDK: 21
Spotbugs: 6.0.3
Spotless: 6.23.3
libGDX: 1.12.1
Gson: 2.10.1

#1312 sollte nach diesem PR rebased & gemerged werden, da es Änderungen in Spotless in der neuen Version gibt.

2023-12-19 12:01 UTC, cagix commented
@fwatermann Hmmm, unter macOS scheint der Schalter im `build.gradle` nicht mehr zu funktionieren:

```
pm-dungeon % ./gradlew run  

> Task :run
operating system 'Mac OS X'
Exception in thread "main" java.lang.IllegalStateException: GLFW may only be used on the main thread and that thread must be the first thread in the process. Please run the JVM with -XstartOnFirstThread. This check may be disabled with Configuration.GLFW_CHECK_THREAD0.
        at org.lwjgl.glfw.EventLoop.check(EventLoop.java:33)
        at org.lwjgl.glfw.GLFW.glfwInit(GLFW.java:1078)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.initializeGlfw(Lwjgl3Application.java:89)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:139)
        at core.game.GameLoop.run(GameLoop.java:105)
        at core.Game.run(Game.java:58)
        at starter.RoomBasedDungeon.main(RoomBasedDungeon.java:34)

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.
```

Das Schräge dabei ist, dass der Schalter ja extra im Task drin ist und bei der Vorgängerversion noch funktioniert hat.

2023-12-19 12:53 UTC, cagix commented
@AMatutat Hast Du auch das Problem auf Deiner Maschine oder bin ich nur zu blöd? IntelliJ versteckt ja auch nochmal die JDK-Version für das Projekt (die hatte ich manuell hochgezogen).

2023-12-19 13:38 UTC, cagix commented
@fwatermann Bitte ersetze im `build.gradle` alle Vorkommen von "`allJvmArgs`" mit "`jvmArgs`"! 

Lt. https://docs.gradle.org/current/dsl/org.gradle.api.tasks.compile.ForkOptions.html ist `allJvmArgs` **read-only** und "_incubating_" - während. man mit `jvmArgs` zusätzliche Argumente setzen kann. 

Mit "`jvmArgs`" läuft es bei mir.

@AMatutat Kannst Du das bitte auch nochmal kurz testen/bestätigen? Dabei bitte aufpassen, dass wirklich JDK21 genommen wird ("`./gradlew --version`" muss was mit "JVM: 21.0.1 ..." rauswerfen ... bzw. IJ muss in den Projekteinstellungen extra überzeugt werden.

2023-12-19 13:55 UTC, cagix requested changes

2023-12-19 13:55 UTC, cagix commented on build.gradle
> +sourceCompatibility = 21
```suggestion
java {
    sourceCompatibility = JavaVersion.VERSION_21
}
```

2023-12-19 13:55 UTC, cagix commented on build.gradle
> +sourceCompatibility = 21
siehe https://docs.gradle.org/8.5/userguide/upgrading_version_8.html#java_convention_deprecation

2023-12-19 13:55 UTC, cagix commented on build.gradle
> +sourceCompatibility = 21
sollte das auch evtl. auch gleich mit hoch nach zeile 17? dann wären die java-versions-sachen an einer stelle.

2023-12-21 23:46 UTC, fwatermann commented
@cagix
Spotless wird aufgrund der Versionsänderung nicht durchlaufen. Ist jetzt die Frage, ob ich die Reformatierung hier mit reinpacke, oder ob wir Spotless jetzt einmal ignorieren, wobei dann JUnit nicht läuft anscheinend.

2023-12-22 07:23 UTC, cagix commented
wieviel änderung an der formatierung würde sich allein durch die neue spotless-version ergeben?

ich denke, die version sollten wir hier machen, und die sich daraus ergebenden formatierungen auch. den switch auf google-format sollten wir nach wie vor in einem separaten pr machen.

was hat das grad mit junit auf sich? nur die version hochziehen sollte doch eigentlich die tests nicht kaputt machen?

2023-12-22 13:43 UTC, fwatermann commented
> was hat das grad mit junit auf sich? nur die version hochziehen sollte doch eigentlich die tests nicht kaputt machen?

Ich hab PowerMock durch die Mockito-Core der aktuellsten Version ersetzt. Aber bevor das war, liefen bei mir einige Tests auch schon nicht. Vermutlich weil Java 21 🤷‍♂️

2023-12-26 13:21 UTC, cagix commented
@fwatermann was ist denn hier der stand? von mir ist noch ein kommentar offen(?), die bemerkung zum schalter für macos ist nicht komplett umgesetzt? und was ist jetzt mit den tests, laufen die wieder?

2023-12-28 17:19 UTC, fwatermann commented
> @fwatermann was ist denn hier der stand? von mir ist noch ein kommentar offen(?), die bemerkung zum schalter für macos ist nicht komplett umgesetzt? und was ist jetzt mit den tests, laufen die wieder?

Die Tests laufen wieder. Den MacOS-Schalter mach ich gerade fertig, hab dein Edit nicht gesehen.

2023-12-29 10:07 UTC, cagix commented
@fwatermann danke! was ich eigentlich meinte war die diskussion https://github.com/Programmiermethoden/Dungeon/pull/1313#pullrequestreview-1788917849 ist noch offen ... 

wenn ich das richtig sehe, hast du das quasi erledigt, zumindest gibt es jetzt einen entsprechenden eintrag ganz oben in zeile 12..17. aber damit ist zeile 63 jetzt obsolet und sollte komplett gelöscht werden, oder? dann kann auch die diskussion "resolved" werden.

2023-12-29 10:08 UTC, cagix commented on build.gradle
> +sourceCompatibility = 21
ok, das ist jetzt implizit erledigt durch zeile 12..17. aber zeile 63 hier müsste bitte noch gelöscht werden, das ist redundant.

2023-12-29 11:06 UTC, cagix requested changes

2023-12-29 11:06 UTC, cagix commented on build.gradle
> +sourceCompatibility = 21
```suggestion
```

2023-12-29 11:06 UTC, cagix commented on build.gradle
> +sourceCompatibility = 21
ich schließe diese conversation und mache eine neue auf mit einem commit-vorschlag, diese zeile einfach zu löschen.

2023-12-29 11:36 UTC, cagix requested changes
noch ein paar aktualisierungen, wo wir schon mal dabei sind

2023-12-29 11:36 UTC, cagix commented on build.gradle
> +    id "com.github.spotbugs" version "6.0.3"
```suggestion
    id "com.github.spotbugs" version "6.0.4"
```

2023-12-29 11:36 UTC, cagix commented on build.gradle
> +    id "com.github.spotbugs" version "6.0.3"
https://plugins.gradle.org/plugin/com.github.spotbugs

2023-12-29 11:36 UTC, cagix commented on build.gradle
>      antlr "org.antlr:antlr4:4.11.1"
```suggestion
    antlr "org.antlr:antlr4:4.13.1"
```

2023-12-29 11:36 UTC, cagix commented on build.gradle
>      antlr "org.antlr:antlr4:4.11.1"
https://mvnrepository.com/artifact/org.antlr/antlr4/4.13.1

2023-12-29 11:36 UTC, cagix commented on build.gradle
>      checkstyleVersion = "10.11.0"
```suggestion
    checkstyleVersion = "10.12.6"
```

2023-12-29 11:36 UTC, cagix commented on build.gradle
>      checkstyleVersion = "10.11.0"
https://github.com/checkstyle/checkstyle/releases

2023-12-29 11:36 UTC, cagix commented on build.gradle
>      implementation group: "com.google.code.gson", name: "gson", version: gsonVersion
```suggestion
    implementation "com.google.code.gson:gson:$gsonVersion"
```

2023-12-29 15:53 UTC, cagix commented
hmmm, checkstyle fehlt jetzt was?

2023-12-29 15:54 UTC, fwatermann commented
> hmmm, checkstyle fehlt jetzt was?

Da scheint es compatiblitätsprobleme zu geben. Mit 10.11.0 läufts 🤷‍♂️

2023-12-29 16:00 UTC, cagix commented
@fwatermann probier mal bitte noch https://mvnrepository.com/artifact/com.puppycrawl.tools/checkstyle/10.12.6 in die gradle-config einzubauen

2023-12-29 16:09 UTC, cagix commented
> > hmmm, checkstyle fehlt jetzt was?
> 
> 
> 
> Da scheint es compatiblitätsprobleme zu geben. Mit 10.11.0 läufts 🤷‍♂️ 

irgendwie scheint das ding zwei libs nicht auflösen zu können? sollte das nicht automatisch rekursiv erfolgen? ich glaube nicht, dass wir dieses guava-zeugs direkt ziehen? oder kommt das über doe json-lib (von @AMatutat eingebaut) mit rein und beisst sich dann?

2023-12-29 16:13 UTC, cagix commented
so langsam habe ich echt immer weniger lust auf dieses projekt :( ... 

@AMatutat wieso werden für checkstyle die regeln extra konfiguriert im build.gradle, aber die suppression-regeln liegen dann wieder im default-config-ordner? warum ist das nicht einheitlich?

2024-01-02 08:49 UTC, cagix commented on build.gradle
> +    checkstyleVersion = "10.12.6"
```suggestion
    checkstyleVersion = "10.12.7"
```

2024-01-02 08:49 UTC, cagix reviewed
Checkstyle: https://github.com/checkstyle/checkstyle/issues/14123

2024-01-02 08:49 UTC, cagix commented on build.gradle
> +    checkstyleVersion = "10.12.6"
```suggestion
    checkstyleVersion = "10.12.7"
```

2024-01-02 09:10 UTC, cagix commented
Entscheidung 02.01.24: Wir setzen hier erstmal die alte Checkstyle-Version wieder ein, damit der PR zugeht. Parallel ein Ticket, um Checkstyle rauszuwerfen: #1316

2024-01-02 09:19 UTC, cagix approved these changes
lgtm (see #1316)

2024-01-02 09:19 UTC, merged

2024-01-02 15:50 UTC, AMatutat commented
> so langsam habe ich echt immer weniger lust auf dieses projekt :( ...
> 
> @AMatutat wieso werden für checkstyle die regeln extra konfiguriert im build.gradle, aber die suppression-regeln liegen dann wieder im default-config-ordner? warum ist das nicht einheitlich?

Historisch gewachsen. Den Basic-Setup haben wir damals aus dem ersten Dungeon Projekt mitgenommen und da wir nie wirklich glücklich mit unserer Checkstyle-Config (und irgendwie auch unsere Projektstruktur) waren, hat sich das schlichtweg keiner angeschaut. Das gesamte Build-Zeugs ist eher on the fly zusammengesteckt als wirklich konzeptioniert.

2024-01-02 16:17 UTC, cagix commented
> > so langsam habe ich echt immer weniger lust auf dieses projekt :( ...
> > @AMatutat wieso werden für checkstyle die regeln extra konfiguriert im build.gradle, aber die suppression-regeln liegen dann wieder im default-config-ordner? warum ist das nicht einheitlich?
> 
> Historisch gewachsen. Den Basic-Setup haben wir damals aus dem ersten Dungeon Projekt mitgenommen und da wir nie wirklich glücklich mit unserer Checkstyle-Config (und irgendwie auch unsere Projektstruktur) waren, hat sich das schlichtweg keiner angeschaut. Das gesamte Build-Zeugs ist eher on the fly zusammengesteckt als wirklich konzeptioniert.

@AMatutat Hihi ... so sieht das auch aus. Naja, wenn ich dazu komme, gehe ich da mal mit ner großen Forke drüber ;)