Move contrib src to dungeon project
Programmiermethoden/Dungeon pull request #1314
Opened 2023-12-19 00:56 UTC by fwatermann

closes #1306 

Verschiebt das `contrib` package aus `game/src` nach `dungeon/src`

2023-12-19 11:26 UTC, AMatutat commented
tests sollten dann auch verschoben werden. 
Guck dir auch mal die starter in `game/src/starter` an, verwenden die was davon?

2023-12-19 11:59 UTC, cagix commented
> tests sollten dann auch verschoben werden. Guck dir auch mal die starter in `game/src/starter` an, verwenden die was davon?
> 
> (Ja ich wollte auch nur mal wieder was sagen)

true dat.

2023-12-19 13:17 UTC, cagix commented
> tests sollten dann auch verschoben werden. Guck dir auch mal die starter in `game/src/starter` an, verwenden die was davon?
> 
> (Ja ich wollte auch nur mal wieder was sagen)

@AMatutat Gute Frage. Die beiden Demo-Starter verwenden _natürlich_ jede Menge Holz aus `contrib`. Inhaltlich haben beide aber auch nix mit dem Dungeon (DSL) zu tun, d.h. ich würde sie auch nicht nach `./dungeon/src/main/starter/` schieben wollen. 

Meine Motivation für das Verschieben von `contrib` war, dass das Projekt `game` die Basis für PM/Prog2 sein soll und dort nix weiter drin sein sollte außer den wirklich notwendigen minimalen Dingen - im Prinzip würde ich den Unterordner vielleicht sogar per `git subtree` für das jeweilige Semester rauslösen und als Vorlage bereitstellen. Die Klassen in `contrib` sind mehr oder weniger Hausaufgabe. Zusätzlich ist es so, dass das Projekt `dungeon` diese `contrib`-Klassen braucht (zumindest einige davon), um die Aufgaben bereitstellen zu können.

Eigentlich müsste man konsequenterweise die interessanten Stellen der beiden Starterklassen im Einstiegsguide dokumentieren und die beiden Starter löschen. 

@AMatutat Wie siehst Du das?

2023-12-20 11:27 UTC, AMatutat commented
> Eigentlich müsste man konsequenterweise die interessanten Stellen der beiden Starterklassen im Einstiegsguide dokumentieren und die beiden Starter löschen.

Das steht da im Grunde auch schon alles drin. On Paper können die Starter weg, der Quickstart baut eh ein eigenen

2023-12-20 11:36 UTC, cagix commented
> 
> > Eigentlich müsste man konsequenterweise die interessanten Stellen der beiden Starterklassen im Einstiegsguide dokumentieren und die beiden Starter löschen.
> 
> 
> 
> Das steht da im Grunde auch schon alles drin. On Paper können die Starter weg, der Quickstart baut eh ein eigenen 

naja, die starter gehen imho schon über den quickstart hinaus, d.h. ich würde so dinge wie die unterschiedlichen raumgeneratoren schon in den quickstart mit aufnehmen als ausblick ...

2023-12-22 18:14 UTC, cagix requested changes
@fwatermann Im Prinzip sind das die groben Dinge. Wie angemerkt gibt es aber auch noch Tests sowie Assets und Dokumentation, die verschoben werden muss. 

Bei den Assets musst Du gut hinschauen, was wofür benutzt wird :)

Bei der Doku müssen ggf. auch interne Links dann nachgezogen werden.


Die beiden Starter in `game` müssten bitte auch noch weg, da sie viel Krams aus `contrib` verwenden.

2023-12-26 13:21 UTC, cagix commented
@fwatermann was ist hier der stand? machst du noch was?

2023-12-29 11:43 UTC, cagix requested changes
kann es sein, dass der taks "runrandom" nicht mehr gebraucht wird?

2023-12-29 11:52 UTC, cagix commented
@fwatermann ich glaube, die doku passt auch noch nicht. es gibt noch jede menge geschwafel zu levelgeneratoren (graph-based, room-level) in game/doc, dito zu items und crafting. das zeug ist doch jetzt in dungeon/contrib, oder? bitte anpassen, falls das so stimmt.

2024-01-02 09:59 UTC, cagix commented
@fwatermann der #1313 hat durch die versionsänderung von spotless eine leichte umformatierung mitgebracht - deshalb gibt es jetzt hier 'zig mergekonflikte. für das rebasen am besten mal temporär in der `build.gradle` die spotless-version auf `id "com.diffplug.spotless" version "6.23.3"` setzen, neu formatieren und danach dann den rebase machen?

2024-01-03 17:59 UTC, cagix commented
@fwatermann jetzt sind es zwei tage nach unserem meeting. any progress?

2024-01-04 08:45 UTC, cagix commented
@fwatermann immer noch konflikte. vermutlich durch den wechsel von asop auf googlestyle (#1321). damit mir das nicht immer gegen die timeline läuft, habe ich das mal auf "draft" gesetzt. bitte setze auch "ready for review", wenn fertig. und erneuere die review-aufforderung, dann krieg ich ne mail :)

2024-01-10 10:30 UTC, cagix commented on dungeon/assets/animation/missing_texture.png
die wird in `game` gebraucht (`core.utils.components.draw.Animation`) - nicht verschieben.

2024-01-10 10:30 UTC, cagix commented on dungeon/assets/character/blue_knight/attack/attack_left_f0.png
die ganzen knight-animationen werden im quickstart in `game` gezogen - nicht verschieben.

2024-01-10 10:31 UTC, cagix commented on game/assets/dungeon/temple/wall/wall_outer_corner_bottom_left.png
was ist hier passiert? wieso wird ein einzelner teil der animation bearbeitet und dann noch gelöscht?

2024-01-10 10:35 UTC, cagix commented on dungeon/assets/character/blue_knight/attack/attack_left_f0.png
hmmm. `blue_knight` kann gehen, aber `knight` wird im quickstart in game gezogen. die animationen dafür müssten in `game` bleiben.

2024-01-10 10:37 UTC, cagix commented on game/src/starter/RandomDungeon.java
kannst du das statt zu löschen einfach nach `dungeon/starter` verschieben?

2024-01-10 10:37 UTC, cagix commented on game/src/starter/RoomBasedDungeon.java
kannst du das statt zu löschen einfach nach `dungeon/starter` verschieben?

2024-01-12 07:58 UTC, fwatermann commented on dungeon/assets/character/blue_knight/attack/attack_left_f0.png
Also alles was im Quickstart verwendet wird, bleibt in `game`?

2024-01-12 08:00 UTC, fwatermann commented on game/assets/dungeon/temple/wall/wall_outer_corner_bottom_left.png
Okay, das kann ich mir selbst gerade nicht erklären 👀

2024-01-12 08:07 UTC, cagix commented on dungeon/assets/character/blue_knight/attack/attack_left_f0.png
wäre gut, weil sonst der quickstart ja nicht mehr funktioniert. 

aber wenn ich das richtig sehe, ist das eigentlich nur die animation für den einfachen helden ("knight"). wenn du noch was siehst, dann sollte das auch in `game` bleiben.

2024-01-12 08:10 UTC, fwatermann commented on dungeon/assets/character/blue_knight/attack/attack_left_f0.png
Hab gerade noch einmal durchgeschaut, sehe sonst nix weiteres.

2024-01-12 08:36 UTC, fwatermann commented
Hmm, mir ist gerade aufgefallen, dass nur die Assets von `game` beim Bauen der `Starter-Jar` in der Jar landen... 🤔

2024-01-12 09:38 UTC, cagix commented
> Hmm, mir ist gerade aufgefallen, dass nur die Assets von `game` beim Bauen der `Starter-Jar` in der Jar landen... 🤔 Bzw. bei allen arten von Jar.
> 
> @cagix

naja, es gibt scheinbar zwei stellen im [build.gradle](build.gradle), die sich damit beschäftigen: https://github.com/Programmiermethoden/Dungeon/blob/87174d9ec246ab24b724cb2e69c5ab36be163f36/build.gradle#L60 und https://github.com/Programmiermethoden/Dungeon/blob/87174d9ec246ab24b724cb2e69c5ab36be163f36/build.gradle#L66

2024-01-14 14:45 UTC, fwatermann commented
@cagix Jars sind gefixt.

2024-01-15 08:51 UTC, cagix commented on build.gradle
> +project.ext.mainClassName = "starter.BasicStarter"
das wird in #1330 gemacht :)

2024-01-15 08:52 UTC, cagix approved these changes
lgtm - muss ich aber noch mal live alles ausführen/testen, deshalb noch kein merge

2024-01-19 17:43 UTC, cagix approved these changes
@fwatermann mange tak! 👍 

auf dem "papier" sehen die änderungen gut aus. 

ich habe den neuen mini-starter in `game` laufen lassen, dito habe ich einen `dungeon`-starter probiert (aus der ide bzw. per gradle-task). außerdem habe ich ein starter.jar gebaut und die example.dng manuell mit `java -jar ...` gestartet. 

blockly habe ich nicht gestartet, sehe aber keinen grund, warum die änderungen in diesem pr da was kaputt machen sollten.

2024-01-19 17:43 UTC, merged