[GAME] Hitbox System verbessern
Programmiermethoden/Dungeon pull request #31
Opened 2022-10-17 17:14 UTC by AHeinisch

fixes #17 

Ich habe jetzt mal die `Hitbox` erweitert. Was jetzt aktuell vielleicht noch zu einem Problem führen kann, ist nicht quadratische Hitboxen, da ich aus Gründen der Einfachheit beim `Hitbox#collide`, mit statischen Werten angelegt habe anstelle von den Winkelgrenzen jedes Mal neu zu berechnen.

- [x] Kollision zwischen zwei hitboxen
- [x] Monster laufen nicht mehr nur noch gegen die Wand
- [ ] Level überladen, um Hitboxen für Wände anzuwenden
 
Und hier einmal mit 100 `Imp`s selbst nach 10 Minuten bleibt keiner stehen.
![Hitbox pathfinding](https://user-images.githubusercontent.com/32952411/196240432-f70fa5fd-1cec-430b-be8f-d5334d34d82c.gif)

2022-10-18 13:16 UTC, AHeinisch commented
@AMatutat, wie viel Arbeit soll ich hier hereinstecken?

Ich habe jetzt hier erstmal die einfachste Implementation von der Hitbox durchgeführt. Es wird zu jedem Level einfach jedes nicht betretbare Feld genommen und eine eigene Hitbox gebaut. Dann gibt es die Sammlung von allen Level Hitboxen im CollidableLevel welches zusätzlich zu den Feldhitboxen noch eine Hitbox um das Level selbst zieht.

Theoretisch existieren aktuell folgende Probleme:
 1. Selbst mittelgroße Level haben bereits 2000+ nicht betretbare Felder, welche von jedem Monster kontrolliert werden muss.
 2. Selbst Felder welche hinter 3+ Feldern versteckt sind bekommen eine Hitbox.

Bei den Problemen könnte ich mir vorstellen, dass, sobald an jedem Feld eine Wand ist, das Kriterium geändert werden kann, welche Felder eine Hitbox bekommen.
Wenn man will, dass es noch anders optimiert wird, müssten Hitboxen zusammengefasst werden.

2022-10-21 13:04 UTC, AMatutat commented
schau ich mir morgen früh an, sorry für die wartezeit

2022-10-24 10:21 UTC, AMatutat requested changes
Sieht gut aus.
Zwei Fragen/Anregungen, bin mir aber nicht sicher wie gut die sind.

2022-10-24 10:21 UTC, AMatutat commented on code/game/src/collision/CollidableLevel.java
> +public class CollidableLevel {
Wäre `CollisionMap` oderso nicht ein passenderer name?

2022-10-24 10:21 UTC, AMatutat commented on code/game/src/collision/TileCollidable.java
> +public class TileCollidable implements Collidable {
Wäre vermutlich sinnvoller direkt `Tile implements Collidable` zu machen, oder? 
Diese zwischenklasse brauchts dann nicht.

2022-10-24 10:21 UTC, AMatutat commented
> Bei den Problemen könnte ich mir vorstellen, dass, sobald an jedem Feld eine Wand ist, das Kriterium geändert werden kann, welche Felder eine Hitbox bekommen.
Wenn man will, dass es noch anders optimiert wird, müssten Hitboxen zusammengefasst werden.

Ich denke auf dauer sollte das gelöst werden (issue erstellen) aber aktuell reicht der aktuelle stand.

2022-11-01 09:35 UTC, merged