[GAME] IIdle: PatrouilleWalk
Programmiermethoden/Dungeon pull request #352
Opened 2023-02-15 17:19 UTC by fwatermann

Konkrete Implementierung des `IIdle` Interfaces. (fixes #138)

- Entity bewegt sich auf einem Pfad.
- Verschiedene Modi:
	- RANDOM: Entity bewegt sich immer zu einem zufälligen nächsten Checkpoint
	- LOOP: Entity läuft alle Checkpoints in einer Reihenfolge ab. Diese Reihenfolge wiederholt sich
	- BACK_AND_FORTH: Entity läuft Checkpoints vorwärts und rückwärts ab.
- Dauer der Pause an einem Checkpoint einstellbar.

2023-02-15 20:10 UTC, AMatutat commented
@fwatermann wenn ein PR soweit fertig ist, bitte ein Review-Request an mich

2023-02-16 13:43 UTC, fwatermann commented
@AMatutat Ja ich weiß. Ich habe die Klasse allerdings noch nicht getestet. Daher noch kein Review-Request

2023-02-19 22:03 UTC, AMatutat requested changes
Sieht schonmal sehr gut aus. Freu mich wie das kleine Vieh rumläuft
Hab Kleinigkeiten anzukreiden.

2023-02-19 23:57 UTC, fwatermann commented on game/src/ecs/entities/TestEntity.java
> +public class TestEntity extends Entity {
Woops. Ja wollte ich eigentlich auch machen :/

2023-02-20 00:32 UTC, fwatermann commented on game/src/ecs/components/ai/idle/PatrouilleWalk.java
> +        Random rnd = new Random();
Gute Idee!

2023-02-20 01:49 UTC, fwatermann commented on game/src/ecs/components/ai/idle/PatrouilleWalk.java
> +            arrivalTime = System.currentTimeMillis();
Okay der Konsistenz her macht das Sinn.

Gibt es denn eine Möglichkeit auf die aktuellen FPS bzw. die target FPS zuzugreifen?

2023-02-20 07:00 UTC, AMatutat commented on game/src/ecs/components/ai/idle/PatrouilleWalk.java
> +            arrivalTime = System.currentTimeMillis();
> target FPS zuzugreifen?

Jop. `Constants.FRAME_RATE`

2023-02-27 09:35 UTC, AMatutat approved these changes

2023-02-27 09:36 UTC, merged