[GAME] ITransition: SelfDefend
Programmiermethoden/Dungeon pull request #368
Opened 2023-02-19 16:32 UTC by AHeinisch

#142 

Implementation von ITransition welche, sobald eine Entity Schaden nimmt in den Kampfmodus wechselt. Und im Prinzip erst wieder aufhört, sobald die Entity wieder komplett geheilt ist.

- Implementation
- Tests

2023-02-19 21:47 UTC, AMatutat commented on game/test/ecs/components/ai/transition/SelfDefendTest.java
> +    public void canBeCreated() {
Das find ich irgendwie seltsam.
Macht man das?

2023-02-19 21:50 UTC, AMatutat requested changes
Sieht gut aus,
kleinkram bzgl der Test.


Mir gefällt die sehr konkrete Fehlermeldung, gut gemacht.

2023-02-19 21:50 UTC, AMatutat commented on game/test/ecs/components/ai/transition/SelfDefendTest.java
> +        entity.addComponent(hc);
das ist nicht nötig, im ctor vom Component wird das schon gemacht
```suggestion
```

2023-02-19 21:50 UTC, AMatutat commented on game/test/ecs/components/ai/transition/SelfDefendTest.java
> +        entity.addComponent(hc);
```suggestion
```

2023-02-20 10:37 UTC, AMatutat approved these changes
lgtm

@AHeinisch mergen?

2023-02-20 11:03 UTC, AHeinisch commented
ja habe nochmal über die doc geguckt ob ich da etwas unstimmiges entdecke aber nein. 

Somit darf gemerged werden

2023-02-20 11:06 UTC, merged