[GAME] SkillSystem
Programmiermethoden/Dungeon pull request #395
Opened 2023-02-24 13:54 UTC by Lena241

fixes #125 & #222

- SkillSystem implementiert
    - zählt den Cool Down aller Skills runter
   
- Skill wird bei Button Press ausgelöst
   - KeyboardSystem heißt jetzt PlayerSystem, da so besser klar wird, dass es sich um die Steuerung des Spielers handelt
   - keine Slots, wie in #222, da noch kein Bedarf dafür besteht, dafür zwei feste Skills auf den Tasten Q und E per getter in Hero

- Tests angepasst

Noch fehlend:
- [ ] Dokumenatation

2023-02-27 10:11 UTC, AMatutat reviewed
hab mal flott drüber geguckt

2023-02-27 10:29 UTC, AHeinisch commented on game/src/ecs/systems/PlayerSystem.java
> +                                else if (Gdx.input.isKeyPressed(Input.Keys.E))
@Lena241 darf das "E" behalten ich werde es anpassen

2023-02-27 10:30 UTC, cagix commented on game/src/ecs/systems/PlayerSystem.java
> +                                else if (Gdx.input.isKeyPressed(Input.Keys.E))
@AHeinisch @Lena241 @AMatutat Wäre es sinnvoll, so etwas "zentral" zu regeln und hier nur auf Variablen/Referenzen zuzugreifen?

2023-02-27 10:36 UTC, AMatutat commented on game/src/ecs/systems/PlayerSystem.java
> +                                else if (Gdx.input.isKeyPressed(Input.Keys.E))
Hab ich eben auch schon überlegt.
"Zentral" ist glaub relativ, das wird nur in dieser Klasse gebraucht, da passt es dann ganz gut hin. Vielleicht oben irgendwie als `finale` Attribut anlegen, damit es übersichtlicher ist.  

Richtig cool wäre natürlich eine Datei in der die Tastenbelegung drinnen steht und man die dann selbst konfigurieren kann (auch als 
Spieler).

2023-02-27 10:46 UTC, cagix commented on game/src/ecs/systems/PlayerSystem.java
> +                                else if (Gdx.input.isKeyPressed(Input.Keys.E))
> Richtig cool wäre natürlich eine Datei in der die Tastenbelegung drinnen steht und man die dann selbst konfigurieren kann (auch als Spieler).

Genau das. 

Sowas könnte beim Start eingelesen werden und in die entsprechenden Systems gesetzt werden (statische Variablen der Systeme).

2023-02-27 10:50 UTC, AMatutat commented on game/src/ecs/systems/PlayerSystem.java
> +                                else if (Gdx.input.isKeyPressed(Input.Keys.E))
#398

2023-03-08 12:28 UTC, AHeinisch commented on game/test/ecs/components/SkillTest.java
> +    public void execute() {
Warum wurden hier die Testmethoden so stark verändert?
Von leicht nachzuverfolgenden zu einer Großen, welche einen nicht hilft irgendwas genau zu testen.

2023-03-15 08:33 UTC, AMatutat submitted a review, later dismissed
lgtm

2023-03-15 08:34 UTC, AMatutat commented on game/test/ecs/components/SkillTest.java
> +    public void execute() {
@Lena241 mach mal ein einges Issue für die Tests. Für Dokumentation hab ich dir schon eins angelegt

2023-03-15 08:57 UTC, AMatutat approved these changes

2023-03-15 09:01 UTC, AMatutat commented on game/src/ecs/systems/PlayerSystem.java
> +        else if (Gdx.input.isKeyPressed(KeyboardConfig.INTERACT_WORLD.get()))
fair point.
@Lena241 mach mal else raus

2023-03-15 09:09 UTC, AMatutat approved these changes

2023-03-15 09:11 UTC, AMatutat requested changes

2023-03-15 09:11 UTC, AMatutat commented on dungeon_config.json
> +{
das ist doch ignore. oder? raus damit

2023-03-15 09:21 UTC, AMatutat approved these changes
most approved pr ever

2023-03-15 09:25 UTC, merged