[GAME] cleanup Framework
Programmiermethoden/Dungeon pull request #401
Opened 2023-02-28 12:13 UTC by AMatutat

- [x] Überflüssige Klassen entfernen
- [x] Sinnvolle Methoden auf ECS Elemente anpassen (alles was ich auf den ersten Blick erkannt habe, der Rest wird mit der Zeit kommen)
- [ ] `ControllerLayer` anschauen, könnte sinnlos sein, könnte bei #244 helfen.
- [ ] Test anpassen 
  - Der `DungeonCamera` Test macht noch Probleme, das liegt aber an Moskito. Muss ich mir genauer anschauen

2023-03-01 09:43 UTC, AMatutat commented
WTF?!
Ich weiß gar nicht wie ich das erklären soll.

Ich wollte die Klasse `controller.Game` nach `starter.Game` verschieben.
Das findet der test in `test/controller/GameTest` aber nicht so durfte, weil er dann (warum er das überhaupt darf ist mir schleierhaft) nicht mehr auf die PROTECTED Methoden in `Game` zugreifen darf. 
Jetzt kommt aber der Knaller, wenn ich das package `test/controller/` int `test/starter/` umbenenne ist er wieder glücklich. 
Das ist doch auf so vielen ebenen Falsch....

2023-03-01 09:56 UTC, cagix commented
> @cagix Ich bin grade am Überlegen, ob ich nicht einfach alles in `pm-dungeon` nach `game` schiebe (andersrum wäre netter, aber dann platzen die ganzen (lokalen) Branches).

Wenn ich das richtig sehe, ist "pm-dungeon" + "game" eigentlich die aktuelle Version unseres Frameworks inkl. ein paar ausformulierter Spielelemente. Insofern macht ein vollständiger Merge in ein einziges Java-Projekt durchaus Sinn.

Die vorgeschlagene Merge-Richtung ist für die aktuelle Entwicklung transparent, und hat bis auf den Namen eigentlich keine Nachteile.

Und "game" als Java-Projekt-Namen für das Framework finde ich eigentlich auch nicht so schlimm.

Ich würde dann aber doch nochmal drüber nachdenken, das Repo wieder nach "PM-Dungeon" umzubenennen.


> Wenn die Dugeon aufgaben für PM stehen, können wir dann die Inhalte die eigentlich schon Lösungen sind, aus dem `game`-Projekt extrahieren.

Hmmm, da bin ich auch am überlegen. Die Frage wäre dann: Wo willst Du diese Inhalte hinschieben - die sollten für die Studis ja quasi unsichtbar sein und für uns aber problemlos zugreifbar? 

Vermutlich muss man eher die Aufgaben für die Studis entsprechend anpassen: Unser Code kann (und sollte) als Studienobjekt dienen, und die Studis sollen was komplexeres bauen? Das wäre auch ein guter Grund, unsere Sachen/Lösungen eher basic zu halten und nur genau das zu implementieren, was wir für das Projekt brauchen.

Unrelated: Sollten wir nach dem Merge von "pm-dungeon" + "game" => "game" die konkreten Spielelemente schrittweise in separate Packages refactorn? Dann hätten wir ganz klar die Trennung zw. Basisframework und unserer Beispielversion eines Helden und verschiedener Skills und ... auf Package-Ebene. Die Frage ist aber vermutlich: Wo genau ist die Grenze, also was ist Framework und was ist konkretes Game? 


> Das ganze soll am Ende ja eh zusammengefügt werden. Also spricht nichts dagegen. Ich krieg nur das Bauchgefühl von "hin und her" irgendwie nicht weg, aber ich weiß auch nicht so richtig warum.

Ich glaube, Dein Unwohlsein beruht darauf, dass Du das Ding einerseits als "Framework" sehen möchtest, und andererseits ist es eine Ausformulierung eines konkreten Spiels (also im Sinne der PM-Studis eine mögliche "Lösung") für das Dungeon-Projekt. Und das gleichzeitig in einem Projekt.

Wenn man es mehr als Framework sehen möchte, müsste man doch wieder zwei Packages (oder besser sogar getrennte Java-Projekte?) machen: Framework und konkretes Spiel. 

Andererseits dient das "Framework" zuallererst dem Unterricht, und den Studis ist die exakte Trennung eher egal. Ich glaube, viele würden sich freuen, wenn sie eine Art rudimentäre Lösung für bestimmte Dinge sehen würden und darauf aufbauen könnten - das bietet etwas Orientierung im Raum der vielen Möglichkeiten. Insofern würde ich eher nicht den "puren" Framework-Gedanken in den Vordergrund stellen.

2023-03-01 09:58 UTC, cagix commented
> WTF?! Ich weiß gar nicht wie ich das erklären soll.
> 
> Ich wollte die Klasse `controller.Game` nach `starter.Game` verschieben. Das findet der test in `test/controller/GameTest` aber nicht so durfte, weil er dann (warum er das überhaupt darf ist mir schleierhaft) nicht mehr auf die PROTECTED Methoden in `Game` zugreifen darf. Jetzt kommt aber der Knaller, wenn ich das package `test/controller/` int `test/starter/` umbenenne ist er wieder glücklich. Das ist doch auf so vielen ebenen Falsch....

Hmmm. Das passt doch? Wenn `Game` im Package `starter` ist, dann kann der Test im Package `controller` eben nicht mehr auf die `protected`-Sachen zugreifen - das würde ja über die Packagegrenze gehen? Oder lese ich das falsch?

2023-03-01 10:01 UTC, AMatutat commented
@malt-r @cagix @AHeinisch ich hab euch jetzt mal gezielt als Reviewer eingetragen, um die unterschiedlichen Blickwinkel abbilden zu können. 
Für mich ist vor allem wichtig: 
- Fällt euch irgendwo ein Konzeptioneller Fehler auf (@cagix , @malt-r)
- Hab ich wichtigen Code gelöscht (@AHeinisch)

2023-03-01 10:06 UTC, AMatutat commented
> Hmmm. Das passt doch? Wenn Game im Package starter ist, dann kann der Test im Package controller eben nicht mehr auf die protected-Sachen zugreifen - das würde ja über die Packagegrenze gehen? Oder lese ich das falsch?

Hänge ich grade? Protected ist doch "nur für mich und sub-klassen". Das andere ist doch package.

2023-03-01 10:08 UTC, AHeinisch commented
> > Hmmm. Das passt doch? Wenn Game im Package starter ist, dann kann der Test im Package controller eben nicht mehr auf die protected-Sachen zugreifen - das würde ja über die Packagegrenze gehen? Oder lese ich das falsch?
> 
> Hänge ich grade? Protected ist doch "nur für mich und sub-klassen". Das andere ist doch package.

naja in Java ist es wie folgt
private nur für mich
package nur für mich und die im selben package/ordner
protected oder auch meisst packageprotected für mich die im selben ordner und alle subklassen
public jeder 
hoffe das hilft =)

2023-03-01 10:11 UTC, cagix commented
> > > Hmmm. Das passt doch? Wenn Game im Package starter ist, dann kann der Test im Package controller eben nicht mehr auf die protected-Sachen zugreifen - das würde ja über die Packagegrenze gehen? Oder lese ich das falsch?
> > 
> > 
> > Hänge ich grade? Protected ist doch "nur für mich und sub-klassen". Das andere ist doch package.
> 
> naja in Java ist es wie folgt private nur für mich package nur für mich und die im selben package/ordner protected oder auch meisst packageprotected für mich die im selben ordner und alle subklassen public jeder hoffe das hilft =)

> ... the protected keyword allows access from sub-classes and members of the same package. (Quelle: https://www.baeldung.com/java-protected-access-modifier)

2023-03-01 10:12 UTC, AMatutat commented
> protected oder auch meisst packageprotected für mich die im selben ordner und alle subklassen

Ha, das wusste ich natürlich. Hab euch nur getestet.

2023-03-02 18:27 UTC, cagix requested changes
Sieht auf den ersten Blick ok aus. 

- [ ] Ein paar Formatverbesserungen habe ich direkt als Vorschlag eingegeben. 


Dann habe ich noch ein paar Fragen: 

- [ ] Bei `api/src/dslToGame/TestComponent.java` bin ich mir nicht sicher, ob diese Datei überhaupt in die API gehört? Das sieht mir nach einem "Proof-of-Concept" aus oder so? Bitte nochmal prüfen.

- [ ] Sollte die Klasse `api/src/quest/Evaluateable.java` nicht eher "Evaluable" heissen? Das Word "Evaluatable" gibt es zwar auch, aber das wirkt auf meine Augen sehr seltsam.

- [ ] Die `api/src/quest/Quest.java` wirkt auf mich nicht ganz klar: Ich instantiiere das Ding mit einer `QuestConfig`, die ich auch intern halte. Aber warum packe ich die Werte in diesem Konfigurationsobjekt zusätzlich noch aus? Und die Methode `getGenerator()` liefert ein nicht initialisiertes Attribut zurück? ... Ich sehe das Ding eher als Record, wo ich für die abstrakten Methoden bereits Callbacks (Lambdas, Methodenreferenzen) übergebe und die im Record in den jetzt abstrakten Methoden einfach aufrufe. So hätte man eine Questklasse, die man nicht zwingend ableiten müsste (außer man will wirklich zusätzliche Zustände und Methoden implementieren)?

- [ ] Ist das Java-Projekt "api" nicht noch viel zu dünn? Was ist das Ziel dieses Projekts, was soll hier genau rausgekapselt werden? Ich sehe einmal die Brücke zur DSL und einmal die Quests, wobei beide Sachen auf mich erstmal zufällig wirken bzw. nichts miteinander zu tun haben? Irgendwie hatte ich unter "api" die Dungeon-API erwartet, also alle Interfaces und Sachen, die man als Nutzer dann greifen und erweitern kann?

- [ ] Ist `game/src/controller/ControllerLayer.java` wirklich ein "ControllerLayer" oder nicht eher ein "LayerController"?

- [ ] Ist `game/src/controller/Game.java` wirklich ein "Controller"? Ich hätte das Ding als eine Art Einsprungpunkt gesehen, wo alles zusammengebaut wird (also Controller, Components, Systeme, ...)? Also vermutlich unter `starter/`?
    - [ ] Damit zusammenhängend: Wir haben auch noch `game/src/starter/ECS.java`... Sollten diese beiden Klassen nicht gemergt werden?

- [ ] Haben die Sachen unter "ecs/components/" wirklich was mit Components zu tun? "AI" wirkt auf mich eher wie etwas aus dem Bereich "System"? Und falls doch/ja, sollten die Compenents nicht alle ein Namensschema "XyzComponent" haben?

- [ ] Wie ordnet sich ein Item (`game/src/ecs/items/Item.java`) im ECS ein? Ist das eher ein "E", also eine Entität? Sollte das dann unter `ecs/entities/` liegen?

2023-03-03 08:01 UTC, AMatutat commented
>  Ist das Java-Projekt "api" nicht noch viel zu dünn? Was ist das Ziel dieses Projekts, was soll hier genau rausgekapselt werden? Ich sehe einmal die Brücke zur DSL und einmal die Quests, wobei beide Sachen auf mich erstmal zufällig wirken bzw. nichts miteinander zu tun haben? Irgendwie hatte ich unter "api" die Dungeon-API erwartet, also alle Interfaces und Sachen, die man als Nutzer dann greifen und erweitern kann?

Okay, vielleicht ist der Name `api` doof. In diesem Projekt soll alles was mit dem Übergang zwischen DSL-Eingabe und Dungeon zu tun hat gekapselt werden. Das wird zu 100% eh nicht gehen, die Annotations müssen in `game` liegen. 
Die Studis rennen in meinen Augen später in/mit `game` rum, denen ist die `api` egal. 
Noch ist das Projekt sehr dünn. @malt-r kann/wird bestimmt noch einiges dorthin auslagern können und aus Dungeon sicht kommt bestimmt auch noch was dorthin.

Ziel hinter der Geschichte ist für mich das eigentliche Framework so simpel wie möglich zu halten. Wenn ich ein zweit Semester bin, würde mich dieser ganze DSL Anbindungszauber sehr verwirrend.



> Haben die Sachen unter "ecs/components/" wirklich was mit Components zu tun? "AI" wirkt auf mich eher wie etwas aus dem Bereich "System"? Und falls doch/ja, sollten die Compenents nicht alle ein Namensschema "XyzComponent" haben?

`ai` ist der name das Packages. Das Component heißt entsprechend `AIComponent`. 
 Der Rest ist definiert die Verhaltensweise. Und ja, das ist wieder schwer mit einem reine ECS in Verbindung zu bringen. 
Components speichern eigentlich nur Daten, wir "tricksen" hier aber und interpretieren Verhalten als eine Form von Daten. 
So können wir unterschiedliches Verhalten bei gleichen Components realisieren. 
Systeme implementieren allgemeingültig Regeln: Quasi die physikalischen Gesetze.
Ganz wichtig ist aber, das ein Component nie etwas von sich aus macht, es muss immer ein System kommen und sagen "mach mal was". 
@AMatutat Das muss in die Doku. Aber weniger verwirren geschrieben. 

> Wie ordnet sich ein Item (game/src/ecs/items/Item.java) im ECS ein? Ist das eher ein "E", also eine Entität? Sollte das dann unter ecs/entities/ liegen?

@AHeinisch wir haben damals darüber gesprochen und es als magische Mischform festgehalten aber jetzt mit etwas Abstand drauf geguckt: Ein Item ist doch eigentlich ein Component, oder? Und die `onDrop` würde nicht eine neue Entität erzeugen, sondern der related entity ein PositionComponent,AnimationComponent und HitboxComponent geben. Beim aufsammeln würden die dann wieder entfernt werden.

2023-03-03 08:22 UTC, cagix commented
> > Ist das Java-Projekt "api" nicht noch viel zu dünn? Was ist das Ziel dieses Projekts, was soll hier genau rausgekapselt werden? Ich sehe einmal die Brücke zur DSL und einmal die Quests, wobei beide Sachen auf mich erstmal zufällig wirken bzw. nichts miteinander zu tun haben? Irgendwie hatte ich unter "api" die Dungeon-API erwartet, also alle Interfaces und Sachen, die man als Nutzer dann greifen und erweitern kann?
> 
> Okay, vielleicht ist der Name `api` doof. In diesem Projekt soll alles was mit dem Übergang zwischen DSL-Eingabe und Dungeon zu tun hat gekapselt werden. Das wird zu 100% eh nicht gehen, die Annotations müssen in `game` liegen. Die Studis rennen in meinen Augen später in/mit `game` rum, denen ist die `api` egal. Noch ist das Projekt sehr dünn. @malt-r kann/wird bestimmt noch einiges dorthin auslagern können und aus Dungeon sicht kommt bestimmt auch noch was dorthin.

Hmmm. "DSL-API" oder "DSL-Connector" dann? Mir war das Ziel dieses Java-Projekts aus dem Namen heraus tatsächlich nicht klar.


> Ziel hinter der Geschichte ist für mich das eigentliche Framework so simpel wie möglich zu halten. Wenn ich ein zweit Semester bin, würde mich dieser ganze DSL Anbindungszauber sehr verwirrend.

Genau so sehe ich das auch, habe mich aber in der vorgeschlagenen Struktur nicht so richtig zurechtgefunden. 

Aus dem Bauch heraus würde ich das "Framework" an sich erwarten, auf dem die Studis aufbauen können, die "DSL-Anbindung" und die "DSL" selbst, und dann tatsächlich noch sowas wie "Game" oder "Puzzles" mit den ausimplementierten Spielelementen/Spielmechaniken für unsere Rätsel (die man aber auch unabhängig davon nutzen könnte). 

Was man vermutlich durchdenken sollte: Macht eine Trennung "Framework" und "Puzzles" wirklich Sinn oder sollte man das besser als ein Projekt "Game" verkaufen (so wie es jetzt im Grunde ist)?



> > Haben die Sachen unter "ecs/components/" wirklich was mit Components zu tun? "AI" wirkt auf mich eher wie etwas aus dem Bereich "System"? Und falls doch/ja, sollten die Compenents nicht alle ein Namensschema "XyzComponent" haben?
> 
> `ai` ist der name das Packages. Das Component heißt entsprechend `AIComponent`. Der Rest ist definiert die Verhaltensweise. Und ja, das ist wieder schwer mit einem reine ECS in Verbindung zu bringen. Components speichern eigentlich nur Daten, wir "tricksen" hier aber und interpretieren Verhalten als eine Form von Daten. So können wir unterschiedliches Verhalten bei gleichen Components realisieren. Systeme implementieren allgemeingültig Regeln: Quasi die physikalischen Gesetze. Ganz wichtig ist aber, das ein Component nie etwas von sich aus macht, es muss immer ein System kommen und sagen "mach mal was". @AMatutat Das muss in die Doku. Aber weniger verwirren geschrieben.

Unter dem Package `AI` sehe ich aber lauter Klassen, nicht scheinbar nicht Components sind? `game/src/ecs/components/ai/AITools.java`, `game/src/ecs/components/ai/fight/CollideAI.java` und `game/src/ecs/components/ai/fight/MeleeAI.java` sollen ja im PR hinzugefügt werden unter `game/src/ecs/components/`? Dito `game/src/ecs/components/ai/idle/PatrouilleWalk.java` ...

2023-03-03 08:24 UTC, AMatutat commented
>  Ist game/src/controller/Game.java wirklich ein "Controller"? Ich hätte das Ding als eine Art Einsprungpunkt gesehen, wo alles zusammengebaut wird (also Controller, Components, Systeme, ...)? Also vermutlich unter starter/?

Jop. Kommt noch aus der alten `MainController` Zeiten. 
Habs gemerged aber die Test krieg ich auf anhieb nicht gefixt #445

2023-03-03 08:25 UTC, AMatutat commented
> Ist game/src/controller/ControllerLayer.java wirklich ein "ControllerLayer" oder nicht eher ein "LayerController"?

Ne der name passt schon. Das Ding ist ein Layer für einen Controller. Ein `LayerController` würde Layer kontrollieren.

2023-03-03 08:29 UTC, cagix commented
> > Ist game/src/controller/ControllerLayer.java wirklich ein "ControllerLayer" oder nicht eher ein "LayerController"?
> 
> Ne der name passt schon. Das Ding ist ein Layer für einen Controller. Ein `LayerController` würde Layer kontrollieren.

OK, verstehe ich inhaltlich grad nicht (was ist ein Layer für einen Controller?), aber müsste dass dann nicht wo anders zu finden sein? Unter `controller/` würde ich nur Controller erwarten?

2023-03-03 08:31 UTC, AMatutat commented
> Unter dem Package AI sehe ich aber lauter Klassen, nicht scheinbar nicht Components sind? game/src/ecs/components/ai/AITools.java, game/src/ecs/components/ai/fight/CollideAI.java und game/src/ecs/components/ai/fight/MeleeAI.java sollen ja im PR hinzugefügt werden unter game/src/ecs/components/? Dito game/src/ecs/components/ai/idle/PatrouilleWalk.java ...

Sind quasi Helper-Klassen die zum Component gehören. 

> Edit: Hmmm, noch nicht genug Kaffee. D.h. die im PR hinzukommenden Sachen unter AI sind nicht die Components für "AI", sondern Verhalten, welches per Definition nicht in die Components darf und aber auch nicht zu einem System gehört?

In diesen PR kommt doch nix unter AI hinzu.


> sondern Verhalten, welches per Definition nicht in die Components darf und aber auch nicht zu einem System gehört?

Herzlich willkommen in der Welt der ECS. Wo alles entweder E oder C oder S ist oder irgendwas dazwischen was es aber nicht geben darf. Aber ja, das beschreibt es recht gut. Unity und co lösen sowas über kleine Skripte die man in den Components reinstecken kann. Wir haben das mit unserem Strategy-Pattern Ansatz kopiert.

2023-03-03 08:39 UTC, cagix commented
.o0( GitHub muss endlich mal eine Thread-Struktur für die Diskussions einführen )

2023-03-03 08:39 UTC, AMatutat commented
> OK, verstehe ich inhaltlich grad nicht (was ist ein Layer für einen Controller?), aber müsste das dann nicht wo anders zu finden sein? Unter controller/ würde ich nur Controller erwarten?

Das Layer sortiert die Elemente im Controller. Jedes Element hat ein Layer und je "kleiner" dein Layer vom Wert her ist, desto eher bist du an der Reihe.

Ist halt wieder eine Helper-Klasse die nur für die Controller relevant ist. Ich gruppiere sowas gerne dann auch dort (vgl AIComponent und dessen Helper).

2023-03-03 08:49 UTC, cagix commented
@AMatutat Die noch offenen Punkte im Review oben (https://github.com/Programmiermethoden/Dungeon/pull/401#pullrequestreview-1322343340) sind konzeptionelle Dinge, die vielleicht nochmal ne kurze Diskussion für sich jeweils brauchen. Willst Du einfach entsprechende neue Issues anlegen und die Punkte oben abhaken, dann könnte es hier zum Merge weitergehen. Auch den Namen für "API" könnte man später ja nochmal anpacken, wenn die Diskussion dazu andauern sollte?

2023-03-03 09:04 UTC, AMatutat commented
#447 


Das Quest-Ding stammt eh noch aus unseren PoC Zeiten und ist stark mit #195 verknüpft.

2023-03-03 09:07 UTC, AMatutat commented
@cagix Hab das api-Project nochmal umbenannt. Umbenennungen auf so einer Ebene sind später echt doof, weil es dir dann die lokalen Branches zerreißen kann. 
Rest ist in einem (neuen) Issue

2023-03-03 09:40 UTC, cagix approved these changes
So könnte es gehen - habe aber nur von der Struktur her geprüft und habe es nicht ausprobiert. Das könnte bitte @AHeinisch nochmal machen?

2023-03-03 09:41 UTC, AMatutat commented
das wäre ganz gut. Ich hab zwar immer versucht meine Temporären Dateien zu löschen, aber sicher ist sicher

2023-03-03 13:15 UTC, AHeinisch commented
Ich habe es jetzt mal den Branch ausgechecked alle Temporären Dateien gelöscht sowie Gradle neuladen lassen und es funktioniert anscheinend alles.

2023-03-03 13:18 UTC, merged