[GAME] Items (Usable & Passive) + Stats
Programmiermethoden/Dungeon pull request #450
Opened 2023-03-03 17:55 UTC by fwatermann

(closes #232 closes #236 closes #235)

Beschreibung folgt.

2023-03-10 08:20 UTC, AHeinisch requested changes
Einmal rüber geschaut sieht recht gut aus. Die Issues sind auch echt gemein Formuliert einmal Probleme beseitigen oder Begründen. Soweit ich es sehe Fehlen Tests sowie normale Doku diese bitte auch einmal hinzufügen

2023-03-10 08:20 UTC, AHeinisch commented on game/src/ecs/components/stats/Stats.java
> +public class Stats {
Ich weiß im Issue stand der Name Stats aber ich finde ihn irgendwie nicht passend. Vielleicht passt ja eher so was wie demageMultipliers. Da hier ja eigentlich nur Schadensmodifikatoren liegen und nicht die eigentlichen Stats. Bei Stats würde ich als Beispiel diese Typischen Stamina, Stärke, Dex, Inteligenz erwarten, welche dann wieder jeweils ihre eigenen Faktoren haben. Dies hier ist aber nur mal laut gedacht und nicht als Änderungszwang.

2023-03-10 21:51 UTC, fwatermann commented on game/src/ecs/components/stats/Stats.java
> +public class Stats {
Genau den Gedankengang hatte ich auch 🤔
Ich gucke nochmal ob mir etwas anderes, passenderes einfällt und ändere das dann gegebenenfalls.

2023-03-10 21:52 UTC, fwatermann commented on game/src/ecs/items/ItemActive.java
> +        System.out.printf("Item \"%s\" used by entity %d\n", item.getItemName(), e.id);
Guter Einwand! Diese Zeilen sind tatsächlich aber schon entstanden als es das Inventar im `master` Branch noch nicht gab.

2023-03-10 22:00 UTC, fwatermann commented on game/src/ecs/systems/HealthSystem.java
>          hsd.hc.setCurrentHealthpoints(hsd.hc.getCurrentHealthpoints() - dmgAmount);
Der Teil stammt tatsächlich nicht von mir. Aber ich gucke mir das nochmal an.

2023-03-10 22:02 UTC, fwatermann commented on game/src/ecs/items/ItemPassive.java
> +    public ItemPassive() {
Simmt 😆 
Ich hatte das bei `ItemActive` selbst geändert, weil es mir aufgefallen war... Hier aber anscheinend vergessen 🤦‍♂️

2023-03-11 00:16 UTC, fwatermann commented
Docs liefere ich noch nach ;)

2023-03-11 07:52 UTC, AHeinisch requested changes
Ich habe mir jetzt hier mal Zeit genommen und dir mal so viel wie möglich aufzuschreiben, dass mit dem TLDR soll nicht behoben werden, sondern nur ein "Ja macht Sinn" oder "Nein ist sinnlos" oder so dazu kommen.

Bei den Tests fehlt allgemein das Aufräumen dies war in den HealthSystemTests anscheinend nie vorhanden. 

Mehr finde ich nicht und sieht für mich mittlerweile recht stimmig aus.

2023-03-11 07:52 UTC, AHeinisch commented on game/src/ecs/components/stats/StatsComponent.java
> +     * Get the stats object of the entity
```suggestion
     * Get the DamageModifier object of the entity
```
Öfters steht noch im Doc der alte Name `stats` obwohl dies nun `DamageModifiers` heißt.

2023-03-11 07:52 UTC, AHeinisch commented on game/src/ecs/components/stats/StatsComponent.java
> +     * @return stats object
```suggestion
     * @return DamageModifier object
```
s.o.

2023-03-11 07:52 UTC, AHeinisch commented on game/src/ecs/components/stats/StatsComponent.java
> +     * Overwrite the stats object of the entity
```suggestion
     * Overwrite the DamageModifier object of the entity
```

2023-03-11 07:52 UTC, AHeinisch commented on game/src/ecs/components/stats/StatsComponent.java
> +     * @param damageModifier new stats object
```suggestion
     * @param damageModifier new DamageModifier object
```

2023-03-11 07:52 UTC, AHeinisch commented on game/src/ecs/items/ItemActive.java
> +    public ItemActive(String name, String description, IItemUse callback) {
JDoc verpasst

2023-03-11 07:52 UTC, AHeinisch commented on game/src/ecs/items/ItemPassive.java
> +     * @param damageModifier Stats of the item
```suggestion
     * @param damageModifier DamageModifier of the item
```

2023-03-11 07:52 UTC, AHeinisch commented on game/src/ecs/items/ItemPassive.java
> +     * @param damageModifier Stats of the item
```suggestion
     * @param damageModifier DamageModifier of the item
```

2023-03-11 07:52 UTC, AHeinisch commented on game/src/ecs/items/ItemPassive.java
> +     * Get the stats of the item.
```suggestion
     * Get the DamageModifier of the item.
```

2023-03-11 07:52 UTC, AHeinisch commented on game/src/ecs/items/ItemPassive.java
> +     * @return Stats of the item
```suggestion
     * @return DamageModifier of the item
```

2023-03-11 07:52 UTC, AHeinisch commented on game/src/ecs/items/ItemPassive.java
> +     * @param damageModifier Stats of the item
```suggestion
     * @param damageModifier DamageModifier of the item
```

2023-03-11 07:52 UTC, AHeinisch commented on game/src/ecs/items/ItemPassive.java
> +     * Set the stats of the item.
```suggestion
     * Set the DamageModifier of the item.
```

2023-03-11 07:52 UTC, AHeinisch commented on game/test/ecs/items/ItemActiveTest.java
> +        assertTrue(inventoryComponent.getItems().contains(item));
assertTrue oder assertFalse am besten immer mit einer Message versehen damit man einfacher versteht warum hier etwas true oder false sein sollte.
```suggestion
        assertTrue("ActiveItem needs to be addedd to the Inventory.",inventoryComponent.getItems().contains(item));
```

2023-03-11 07:52 UTC, AHeinisch commented on game/test/ecs/systems/HealthSystemTest.java
> +        Game.entities.clear();
Ich bin mal so gemein, weil ich es hier gerade sehe. Für die nächste Teamrunde vielleicht nochmal mit aufräumen und vorbereiten von Tests besprechen, ob wir nicht doch before und after erlauben, da jeder SystemTest automatisch Klassenattribute nutzt und somit immer wieder von einem anderen beeinflusst werden kann.

Hier reden wir nicht davon das Testrelevante Elemente ausgelagert werden, sondern sowas wie jeder SystemTest braucht ein sauberes `Game.entities` und auch einen `SystemController`. Und am besten, damit nicht ein darauf laufender Test beeinflusst wird sollte die `Game.entites` geleert werden sowie der `SystemController` gelöscht werden.

Zwar gibt es dieses Issue #213 aber ich denke wie dort bereits erwähnt müssen wir einmal drüber nachdenken ob. `Game.entities.clear()` sowie `Game.systems = new SystemController()` nicht wirklich eine Ausnahme sind.

TLDR. Die Tests enthalten "Code duplizierung" welche aber nicht wirklich zum Test gehören. Überdenken von Einschränkungen von setup & cleanup für Test unrelevante vorbereitung bzw. aufräumarbeiten.

2023-03-11 07:52 UTC, AHeinisch commented on game/test/ecs/systems/HealthSystemTest.java
> +        assertTrue(healthComponent.getCurrentHealthpoints() <= 0); // 100 - 10 * 100
s.o. assertMessages bei den boolschen

2023-03-11 07:52 UTC, AHeinisch commented on game/src/ecs/systems/HealthSystem.java
>          hsd.hc.setCurrentHealthpoints(hsd.hc.getCurrentHealthpoints() - dmgAmount);
Ja mein Gedanke war sicher nicht der richtige. Vielleicht bietet es sich an die Methode wo dieser Code drinnen steht. umzubenennen, da setDmgAmount nach einem setter klingt, aber an sich mehr als das gemacht wird. vielleicht irgendwie applyDamage/doDamageToEntity oder so was.

2023-03-12 23:04 UTC, fwatermann commented on game/test/ecs/systems/HealthSystemTest.java
> +        Game.entities.clear();
Ich bin da bei dir. So blähen sich die Testklassen unnötig auf und wirklich JEDER Test braucht die leere `Game.entities` Liste und einen sauberen `SystemController` damit sie unabhängig laufen.

2023-03-13 06:16 UTC, AHeinisch approved these changes
Für mich sieht es hier jetzt ganz gut aus. Vielleicht bin ich aber durch das mehrmalige reviewen jetzt auch leicht codeblind. Ich sehe keine Probleme mit Code oder JavaDoc.

2023-03-13 06:34 UTC, AHeinisch commented on game/test/ecs/systems/HealthSystemTest.java
> +        Game.entities.clear();
Habe es mal im Issue erwähnt und würde das hier unresolved lassen bis wir einmal darüber gesprochen haben.

2023-03-13 08:59 UTC, JudiTeller approved these changes
Mir ist beim Durchschauen so weit auch nichts aufgefallen.

2023-03-15 08:19 UTC, AMatutat approved these changes
lgtm

2023-03-15 08:19 UTC, AMatutat commented on game/test/ecs/systems/HealthSystemTest.java
> +        Game.entities.clear();
ich resolve mal zum mergen

2023-03-15 08:19 UTC, merged