[GAME] add Game Debug Tools
Programmiermethoden/Dungeon pull request #495
Opened 2023-03-21 10:42 UTC by AMatutat

Ich habe ein paar "Debug"-Optionen eingebaut. 

- add class `Debugger` as `ECS_System`
    - Als `ECS_System` da er so "ganz normal" in die Game-Loop integriert werden kann
    - Ist per default deaktiviert und kann mit "B" aktiviert werden
- Funktionen um den Spieler zu Telportieren 
    - Zum Cursor  (Taste O)
    - Zum Level Start (Taste H)
    - Zum Level End (ganz nah dran) (Taste J)
    - Auf das Level End (damit wird das neue Level geladen) (Tage G)
- Funktionen zum rein und raus zoomen (Taste L und Taste K) 
- Funktion um die größe des nächsten Level einzustellen (Taste Y)
- Funktion um ein Monster auf der Cursor Position spawnen zu lassen (Taste X)

Theoretisch kann das Ding jetzt beliebig erweitert werden.

Ich hab noch zwei Fragen:
- Sollte dort auch ein Logger eingebaut werden? Könnte das helfen? 
- Sollten die Debug-Tasten auch in die Config?

2023-03-21 12:01 UTC, AHeinisch commented
Mal ausgeführt und die Handhabung kontrolliert.

> * Ist per default deaktiviert und kann mit "B" aktiviert werden

Ist per Default aktiv und wird im Game direkt deaktiviert. Vielleicht dieses toggleRun also run = false in den ctor, damit es wirklich übereinstimmt.

> * Zum Cursor  (Taste O)

Ich weiß ist vielleicht kleinlich, aber kann, wenn der Cursor außerhalb des Levels ist, zum Crash führen (Also wenn Cursor im x oder y kleiner als 0 wird oder falls der Cursor im x oder y größer wird als das Level selbst) sonst muss noch kenntlich gemacht werden, wo das Level ist. Da Wände/Löcher/Übersprungende ja ebenfalls schwarze Textur haben (oder eher komplett transparent)

> * Funktion um die größe des nächsten Level einzustellen (Taste Y)

Brauch um bedingt ein Logging sonst weis man nicht was gerade ausgewählt wurde, mit Debugger von der IDE kriegt man es raus aber steht dann ja nicht im Log was gemacht wurde.

> * Funktion um ein Monster auf der Cursor Position spawnen zu lassen (Taste X)

Hier dasselbe wie beim zum Cursor nur hier können Monster gespawnt werden, welche einen Crash verursachen.

> * Sollte dort auch ein Logger eingebaut werden? Könnte das helfen?

Ich würde sagen Ja, damit alle Informationen im Log zu finden sind die vielleicht zum Fehler geführt haben.

> * Sollten die Debug-Tasten auch in die Config?

Meiner Meinung ja, da sie ja ggfls zu Konflikten bei der Belegung führen könnten.

2023-03-22 10:30 UTC, AMatutat commented
@AHeinisch Hab dein Feedback umgesetzt.

2023-03-22 10:57 UTC, AHeinisch reviewed
Bin nochmal darüber gegangen habe jetzt nichts mehr gefunden, wo ich sagen würde hält den Merge ab. Nur 2 kleine Fragen zu dem Code und ein vielleicht Verbesserung wo ich aber mir selbst nicht sicher bin.
Sobald du die Diskussionen geschlossen hast, müsste vielleicht nochmal wer anderes darüber schauen, da ich glaube bei diesem Code bald code blind bin. Aber sonst würde ich es auch approven.

2023-03-22 10:57 UTC, AHeinisch commented on game/src/starter/Game.java
> +        if (Gdx.input.isKeyJustPressed(KeyboardConfig.DEBUG_ACTIVATE_DEACTIVATE.get())) {
Kleinigkeit aber DEBUG_TOGGLE_KEY für den Key finde ich irgendwie schöner, aber das ist auch nur meine Ansicht und kann getrost ignoriert werden

2023-03-22 10:57 UTC, AHeinisch commented on game/src/configuration/KeyboardConfig.java
Vielleicht nur, weil ich es jetzt sehe. Vielleicht empfiehlt es sich auf Dauer einmal die config Datei wie sie strukturiert werden soll überlegen. Unübersichtlich, wenn jetzt noch mehr Tasten dazu kommen und auch vielleicht wieder Aspekt schlecht zu warten. Auch wenn es ja eigentlich nur einmal erstellt werden muss, das Programm gestartet werden muss und es erstellt sich die config Vorlage.

2023-03-22 10:57 UTC, AHeinisch commented on game/src/starter/Debugger.java
> +    public static void SPAWN_MONSTER(Point position) {
Dies wird ja später durch #239 ersetzt oder?

2023-03-22 11:07 UTC, AMatutat commented on game/src/configuration/KeyboardConfig.java
mach dafür mal nen neues Issue, ist ein guter Punkt

2023-03-22 11:07 UTC, AMatutat commented on game/src/starter/Debugger.java
> +    public static void SPAWN_MONSTER(Point position) {
Vermutlich.

2023-03-23 15:36 UTC, fwatermann requested changes

2023-03-23 21:54 UTC, fwatermann commented on game/src/configuration/KeyboardConfig.java
> +                    new String[] {"debug", "teleport_cursor"}, new ConfigIntValue(Input.Keys.O));
Zusätzlich dazu: #505

2023-03-27 14:05 UTC, AMatutat commented on game/src/starter/Debugger.java
> +        if (Game.currentLevel.getTileAt(targetLocation.toCoordinate()).isAccessible()) {
Jop. 
Ich hab das jetzt mal so interpretiert: Wenn du beim aufrufen nicht aufpasst, deine Schuld. 
Darum hab ich nen try catch in der `SPAWN_MONSTER_ON_CURSOR` eingebaut.

2023-03-27 14:05 UTC, AMatutat commented on game/src/starter/Debugger.java
> +        if (Game.currentLevel.getTileAt(position.toCoordinate()).isAccessible()) {
s.o

2023-03-27 18:43 UTC, fwatermann commented on game/src/starter/Debugger.java
> +        if (Game.currentLevel.getTileAt(targetLocation.toCoordinate()).isAccessible()) {
Ich weiß nicht ob ich das für eine gute/richtige Lösung halte. In diesem Fall würde sie ja sogar zum Crash führen... Was ich dann doof finde.
Dann lieber Exception abfangen/umgehen und informieren, wobei wir dafür aktuell nicht wirklich eine Möglichkeit grafisch haben, sondern nur via Konsolenausgabe.

2023-03-28 06:32 UTC, AMatutat commented on game/src/starter/Debugger.java
> +        if (Game.currentLevel.getTileAt(targetLocation.toCoordinate()).isAccessible()) {
Habs geändert. Happy?

2023-03-28 23:27 UTC, fwatermann approved these changes

2023-05-10 16:50 UTC, fwatermann submitted a review, later dismissed

2023-05-10 16:50 UTC, fwatermann commented on game/src/starter/Game.java
> +        if (Gdx.input.isKeyJustPressed(KeyboardConfig.DEBUG_ACTIVATE_DEACTIVATE.get())) {
Sollte dieser nicht in `DEBUG_TOGGLE_KEY` umbenannt werden?

```suggestion
        if (Gdx.input.isKeyJustPressed(KeyboardConfig.DEBUG_TOGGLE_KEY.get())) {
```

2023-05-10 16:50 UTC, fwatermann commented on game/src/configuration/KeyboardConfig.java
> +    public static final ConfigKey<Integer> DEBUG_ACTIVATE_DEACTIVATE =
```suggestion
    public static final ConfigKey<Integer> DEBUG_TOGGLE_KEY =
```

2023-05-12 09:56 UTC, AMatutat commented
@cagix da du grade der einzige bist der hier aktiv rumrennt: 
Kannst du mir mal ein lgtm geben? Das Ding ist schon lange durch aber niemand approved meinen Rebase....

2023-05-12 09:59 UTC, cagix reviewed
@AMatutat Interessant. Frage zur API: Die ganzen Hilfsfunktionen sind `static` und `public`. Soll das so, also sollen das wirklich (a) Klassenmethoden und (b) von außen aufrufbar sein?

2023-05-12 10:02 UTC, cagix commented
> @cagix da du grade der einzige bist der hier aktiv rumrennt:
> Kannst du mir mal ein lgtm geben? Das Ding ist schon lange durch aber niemand approved meinen Rebase....

@AMatutat Gern, aber siehe noch meine Frage obendrüber: ist das wirklich gewollt mit `static` und `public`?

2023-05-12 10:45 UTC, AMatutat commented
> @AMatutat Interessant. Frage zur API: Die ganzen Hilfsfunktionen sind static und public. Soll das so, also sollen das wirklich (a) Klassenmethoden und (b) von außen aufrufbar sein

Die Funktionen sind nicht wirklich vom Debugger-Systme abhängig und können daher gerne auch woanders benutzt werden, daher hab ich sie public static gelassen. Das Debugger-System übernimmt für mich nur den Aufruf per Tastendruck. 

Oder in einfach: Macht nix kaputt und kann für den ein oder anderen bestimmt nützlich sein.

2023-05-12 11:15 UTC, cagix approved these changes
> > @AMatutat Interessant. Frage zur API: Die ganzen Hilfsfunktionen sind static und public. Soll das so, also sollen das wirklich (a) Klassenmethoden und (b) von außen aufrufbar sein
> 
> Die Funktionen sind nicht wirklich vom Debugger-Systme abhängig und können daher gerne auch woanders benutzt werden, daher hab ich sie public static gelassen. Das Debugger-System übernimmt für mich nur den Aufruf per Tastendruck.
> 
> Oder in einfach: Macht nix kaputt und kann für den ein oder anderen bestimmt nützlich sein.

Hmmm. Klingt für mich noch nicht so richtig überzeugend. 

Die nächste Frage wäre nämlich: Wieviele Debugger gibt es? Eigentlich ist es ein `System`, d.h. es dürfte zu einem Zeitpunkt nur einen geben (BTW: Wie ist das eigentlich mit unseren Systems, können die mehrfach instantiiert werden oder ist da Singleton drin?) und über den mache ich den Kram. 

Und es gibt zusätzlich vielleicht eine Util-Klasse, die dann statische Methoden anbietet ... 

---

@AMatutat In der Hoffnung, dass Du weisst, was Du tust: ok(ish) ;)

2023-05-12 11:26 UTC, AMatutat commented
> BTW: Wie ist das eigentlich mit unseren Systems, können die mehrfach instantiiert werden oder ist da Singleton drin?
Jetzt wo du es sagst .... #649 

> Und es gibt zusätzlich vielleicht eine Util-Klasse, die dann statische Methoden anbietet ...

Wäre theoretisch auch denkbar. Ich betrachte den Debugger selbst eher als Util und weniger als System (liegt auch nicht im System packages)

2023-05-12 11:27 UTC, merged