[DOC] add Diagramme für neues Itemkonzept
Programmiermethoden/Dungeon pull request #497
Opened 2023-03-22 12:42 UTC by Lena241

@AMatutat wie angefragt, hast du hier die Diagramme für #447 

- Klassendiagramm
- Sequenzdiagramm

2023-03-22 12:53 UTC, malt-r submitted a review, later dismissed

2023-03-22 12:53 UTC, malt-r commented on doc/ecs/item/sequenzdiagramm.png
Ich würde an dem Pfeil von DSL zu worldItem:Entity den `addComponent()` Aufruf mit dem `ItemComponent` ganz nach oben setzen, weil das der für dieses Diagram wichtigste Aufruf ist.

`inventory:InvenotryComponent` (ganz rechts) hat einen Typo.

Ich finde die Beschriftung vom Pfeil von `hero:Hero` zu `worldItem:Entity` "rennt in" nicht aussagekräftig, bzw. zu umgangssprachlich. Was da passiert ist, dass die Hitboxen sich überlappen, so spezifisch können wir da schon werden.
Genauso mit dem Pfeil von `worldItem:Entity` zu `item:Item`: '... lässt worldItem sterben' impliziert, dass es lebt. Ich würde da präziser formulieren und sagen, dass das `worldItem gelöscht wird, "sterben lassen" ist nicht eindeutig.

2023-03-22 16:07 UTC, AMatutat commented
@Lena241 danke. Ich würde ab hier übernehmen und die mit @cagix angesprochenen Änderungen einpflegen.

2023-06-19 08:11 UTC, AMatutat requested changes
class diagram sieht gut aus.
Sequendiagramm fehlt noch

2023-06-19 08:15 UTC, AMatutat requested changes
edit 2: 
schmeiß mal die ganzen getter/setter raus.
a) heißen die bald anders und b) snd die für den Zweck des UMLs Overkill.
Auch die ganzen `default...` Dinger können raus.

2023-06-19 19:59 UTC, AMatutat requested changes
Eine kleinigkeit.
Ansonsten sieht das erstmal gut aus.
Muss mal gucken ob ich es für den eigentlichen Anwendungsfall nochmal entschlacke, aber ich habe noch keine richtige Vorstellung und rauswerfen ist immer einfacher als einbauen.

Dank dir

2023-06-19 19:59 UTC, AMatutat commented on doc/ecs/item/sequenzdiagramm.png
Das AnimationComponent heißt jetzt DrawComponent

2023-06-20 14:53 UTC, Lena241 commented on doc/ecs/item/sequenzdiagramm.png
Das habe ich sogar noch gesehen und daran gedacht... Und dann etwas anderes angepasst.
Ändere ich sofort.

2023-06-20 15:37 UTC, AMatutat approved these changes
lgtm, danke dir

2023-06-20 15:38 UTC, AMatutat commented on doc/ecs/item/sequenzdiagramm.png
@Lena241 guck mal was davon noch up to date ist

2023-06-21 08:21 UTC, AMatutat approved these changes
thx

2023-06-21 08:21 UTC, merged