[Config] Projektstruktur
Programmiermethoden/Dungeon pull request #54
Opened 2022-11-01 09:49 UTC by AMatutat

fixes #50  

- alle inhalte aus `./code` in top level verschoben
- `checkstyle-config/checks.xml => checks.xml`
- `build.gradle` entsprechend angepasst

@cagix @malt-r 
Entspricht das eurer Vorstellung?

2022-11-01 13:25 UTC, malt-r commented
Das passt für mich

2022-11-01 13:25 UTC, malt-r approved these changes

2022-11-02 18:17 UTC, cagix requested changes
@AMatutat Bitte aus PM-Dungeon die Files hierher übernehmen (kopieren): `.gitignore`, `.gitattributes`, `.editorconfig`. 

Das überschreibt zwar Deine Änderung an `.gitignore`, aber das `.DS_Store` ist dort schon drin :)

Ansonsten sieht die Struktur ordentlich aus - übersetzt habe ich es aber nicht, nur manuell/optisch angeschaut...

2022-11-03 11:46 UTC, AMatutat commented
> Das überschreibt zwar Deine Änderung an .gitignore, aber das .DS_Store ist dort schon drin :)

haben wahr, war doppelt gemoppelt

2022-11-03 11:47 UTC, cagix approved these changes

2022-11-03 11:48 UTC, merged