[Game] rename ECS_System into System
Programmiermethoden/Dungeon pull request #597
Opened 2023-05-02 11:17 UTC by AMatutat

fixes #551 

- rename `ECS_System` into `System` 
- UMLs angepasst
- Dokumentation angepasst

2023-05-02 16:03 UTC, cagix requested changes
Sieht gut aus!

`grep -r "ECS_System" *` hat noch einen Kommentar im game/src/controller/SystemController.java gefunden (siehe Änderungsvorschlag).

2023-05-02 16:03 UTC, cagix commented on game/src/controller/SystemController.java
>  /** used to integrate ECS_Systems in PM-Dungeon game loop */
```suggestion
/** used to integrate Systems in PM-Dungeon game loop */
```

2023-05-03 06:04 UTC, cagix submitted a review, later dismissed

2023-05-03 10:46 UTC, AMatutat commented
Ich bin etwas verwirrt weil GitHub aufgrund von Konflikten nicht Mergen wollte, ich aber problemlos rebasen konnte und nicht einen Konflikt hatte...


Ich vermute mal die Dateiumbenennung war schuld(?):

2023-05-03 17:23 UTC, cagix commented
> Ich bin etwas verwirrt weil GitHub aufgrund von Konflikten nicht Mergen wollte, ich aber problemlos rebasen konnte und nicht einen Konflikt hatte...
> 
> Ich vermute mal die Dateiumbenennung war schuld(?):

Seltsamerweise zeigt mir GitHub alle Dateien bis auf eine "geschlossen" an, also bereits gereviewt und keine weiteren Änderungen in der Zwischenzeit. Hmmm.

2023-05-03 17:26 UTC, cagix approved these changes
Alle Dateien bis auf eine werden als "bereits gereviewt" angezeigt, und die eine ist auch OK. 

Ich habe mir den Branch lokal ausgecheckt und nach "ECS_" gesucht und nur noch eine harmlose Referenz gefunden, die aber ok ist. 

D.h. das sollte dann jetzt passen (hoffe ich).

2023-05-10 11:28 UTC, merged