[Game] Implement ITransition: ProtectOnAttack
Programmiermethoden/Dungeon pull request #656
Opened 2023-05-12 19:30 UTC by Pascal378

### Der PR bezieht sich auf folgende Bounties/Issues:

<del>**Fixes_ #144** - Habe ich mal umbenannt in **ProtectOnApproach**, klingt allgemeingültiger, **ProtectTreasure** klang so als könnte man nur Chests damit beschützen. 

<del>Die _ITransition_ wird ausgelöst sobald sich der Held in einer vorbestimmten Range einer ebenso vorgegebenen Entity nähert. Nach einmaligen triggern wechselt diese auch nicht mehr zurück in den Idle-Mode.

<del>**Anmerkung:** Die Tests gestalten sich hier schwierig, ich kriege ständig NullPointerExceptions beim initalisieren des Heros, ein Hero ist aber zum testen nötig. Ich bin leider noch unerfahren mit Mocking, habe aber nicht das Gefühl das es hier eine gute Alternative ist da das Problem tiefer greift. Über Anreize wie man die Tests besser gestalten kann würde ich mich freuen. Hat wohl irgendetwas mit LibGDX zutun.

**Fixes #143** - Habe ich auch umbenannt in **ProtectOnAttack**. Das grenzt beide Transitions denke ich schön voneinander ab. 

Hier kann sowohl eine einzelne Entity als auch eine Liste von Entities übergeben werden. (Würde sich auch anbieten das in der anderen Transition zu implementieren, oder?) 
Erleidet eine Entity Schaden und der "cause" dieses Schadens ist eine Entität mit **PlayableComponent** wird **isInFight** getriggered und nicht mehr zurück gesetzt.

Die Tests sind hier soweit alle durchgegangen. 

Freue mich über euer Feedback dazu!

2023-05-12 20:56 UTC, AMatutat commented
Auf den ersten Blick sieht das gut aus, danke.
Ich schau mir das in kürze nochmal genauer an und gebe dann mehr Feedback.

2023-05-12 20:57 UTC, AMatutat commented on game/src/ecs/components/ai/transition/ProtectOnApproach.java
> +    public ProtectOnApproach(float range, Entity toProtect) {
In der Klassen-Javadoc wird von "mehrere" Entitäten gesprochen, implementiert ist es aber nur für eine

2023-05-12 21:04 UTC, AMatutat requested changes

2023-05-12 21:04 UTC, AMatutat commented on game/src/ecs/components/ai/transition/ProtectOnAttack.java
> +     * @param entity
```suggestion
     * @param entity to protect
```

aber gerne noch etwas ausführlicher

2023-05-12 21:04 UTC, AMatutat commented on game/src/ecs/components/ai/transition/ProtectOnAttack.java
> +    private final List<Entity> toProtect = new ArrayList<>();
das könnte ein Set sein

2023-05-12 21:04 UTC, AMatutat commented on game/src/ecs/components/ai/transition/ProtectOnAttack.java
> +    ProtectOnAttack(List<Entity> entities) {
```suggestion
    ProtectOnAttack(Collection<Entity> entities) {
```

hier reicht ein generischer Typ

2023-05-12 21:04 UTC, AMatutat commented on game/src/ecs/components/ai/transition/ProtectOnAttack.java
> +            .filter(e -> e.getComponent(HealthComponent.class).isPresent())
hmm, oben wird eine Expcetion geworfen, wenn kein HealthComponent in der Entität ist, hier wird das ignoriert.

2023-05-12 21:07 UTC, AMatutat commented
@fwatermann @JudiTeller als Tutoren solltet ihr vermutlich auch mal drauf gucken.

2023-05-12 22:41 UTC, Pascal378 commented
@AMatutat Danke für das Feedback, hab so ziemlich alles was du angesprochen hast versucht umzusetzen und auch gerade mal pushed. Ich werde in der ProtectOnApproach Transition auch noch einen Konstruktor bauen der es erlaubt Listen zu übergeben denke ich. Habe die JavaDoc aber fürs erste so korrigiert das nur von einer Entity die Rede ist.

2023-05-13 14:53 UTC, tgrothe commented
Für das Mocken des Libgdx-Kontexts ist vielleicht Folgendes hilfreich (das Ziel ist es, die Klasse Hero im headless mode zu testen):

```java
package ecs.components.ai.transition;

import com.badlogic.gdx.Gdx;
import com.badlogic.gdx.Graphics;
import com.badlogic.gdx.Input;
import com.badlogic.gdx.backends.lwjgl3.Lwjgl3Files;
import com.badlogic.gdx.graphics.GL20;
import com.badlogic.gdx.graphics.g2d.SpriteBatch;
import com.badlogic.gdx.graphics.glutils.ShaderProgram;
import com.badlogic.gdx.utils.GdxNativesLoader;
import ecs.components.PositionComponent;
import ecs.components.ai.AIComponent;
import ecs.components.ai.fight.CollideAI;
import ecs.components.ai.idle.RadiusWalk;
import ecs.entities.Entity;
import graphic.DungeonCamera;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.powermock.api.mockito.PowerMockito;
import org.powermock.core.classloader.annotations.PrepareForTest;
import org.powermock.modules.junit4.PowerMockRunner;
import starter.Game;
import tools.Constants;
import tools.Point;

import java.util.logging.LogManager;

import static org.junit.Assert.assertTrue;

@RunWith(PowerMockRunner.class)
@PrepareForTest({Game.class, Gdx.class, Constants.class, LogManager.class, Graphics.class, GL20.class, SpriteBatch.class, ShaderProgram.class, DungeonCamera.class})
public class ProtectOnApproachTest {
    private Entity entity;
    private AIComponent entityAI;
    private Entity protectedEntity;
    private Entity hero;
    private final Point pointOfProtect = new Point(0, 0);

    @Before
    public void setUpEntityToProtect() {
        protectedEntity = new Entity();

        //Add AI Component
        AIComponent protectedAI = new AIComponent(
            protectedEntity,
            new CollideAI(0.2f),
            new RadiusWalk(0, 50),
            new RangeTransition(2)
        );

        protectedEntity.addComponent(protectedAI);

        //Add Position Component
        protectedEntity.addComponent(
            new PositionComponent(
                protectedEntity,
                pointOfProtect)
        );
    }

    @Before
    public void setUpEntityThatProtects() {
        entity = new Entity();

        //Add AI Component
        entityAI = new AIComponent(
            entity,
            new CollideAI(0.2f),
            new RadiusWalk(0, 50),
            new ProtectOnApproach(2f, protectedEntity)
        );
        entity.addComponent(entityAI);

        //Add Position Component
        entity.addComponent(
            new PositionComponent(
                entity,
                new Point(0f, 0f))
        );
    }

    @Before
    public void setUpHero() {
//        PowerMockito.whenNew(LogManager.class).withAnyArguments().thenReturn(PowerMockito.mock(LogManager.class));

        GdxNativesLoader.load();
        Gdx.graphics = PowerMockito.mock(Graphics.class);
        Gdx.input = PowerMockito.mock(Input.class);
        Gdx.files = new Lwjgl3Files();
        Gdx.gl = PowerMockito.mock(GL20.class);
        Gdx.gl20 = PowerMockito.mock(GL20.class);
        PowerMockito.mockStatic(SpriteBatch.class);
        PowerMockito.mockStatic(DungeonCamera.class);

        Game game = new Game();
        game.render(0);
        hero = Game.getHero().orElseThrow();
    }

    @Test
    public void testHeroInRange() {
        //when
        hero.removeComponent(PositionComponent.class);
        hero.addComponent(new PositionComponent(hero, pointOfProtect));

        //then
        assertTrue(entityAI.getTransitionAI().isInFightMode(entity));
    }
}
```

In der build.gradle muss Folgendes ergänzt werden:

```
test {
    jvmArgs "--add-opens=java.logging/java.util.logging=ALL-UNNAMED"
    testLogging {
        events "passed", "skipped", "failed"
    }
}
```

Wenn man nun den Test testHeroInRange() aufruft, dann läuft starter.Game#setup komplett durch.

Aber in Zeile 96 (`batch.setProjectionMatrix(camera.combined);`) tritt noch ein Fehler auf, wobei ich etwas ratlos bin:

```
Cannot invoke "com.badlogic.gdx.graphics.g2d.SpriteBatch.setProjectionMatrix(com.badlogic.gdx.math.Matrix4)" because "<local3>" is null
java.lang.NullPointerException: Cannot invoke "com.badlogic.gdx.graphics.g2d.SpriteBatch.setProjectionMatrix(com.badlogic.gdx.math.Matrix4)" because "<local3>" is null
	at starter.Game.render(Game.java:96)
	at ecs.components.ai.transition.ProtectOnApproachTest.setUpHero(ProtectOnApproachTest.java:97)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.internal.runners.MethodRoadie.runBefores(MethodRoadie.java:133)
	at org.junit.internal.runners.MethodRoadie.runBeforesThenTestThenAfters(MethodRoadie.java:96)
```

2023-05-13 16:36 UTC, AMatutat commented
@tgrothe ne ne ne, geh blos weg mit diesen PowerMock mist...

2023-05-13 21:37 UTC, tgrothe commented
@AMatutat dachte, wäre hier hilfreich und angemessen, um die Klasse testen zu können... aber ich bin nicht auf dem neusten Stand, was nun verwendet werden soll...

sollte nur eine Idee/Anregung sein, bin schon 😶

2023-05-17 09:41 UTC, JudiTeller reviewed
Im Ganzen sieht's gut aus. Meine suggestions sind eher auf der nitpicky Seite :smile:

2023-05-17 09:41 UTC, JudiTeller commented on game/src/ecs/components/ai/transition/ProtectOnApproach.java
> +     * If entity that protects isn't in fight mode yet, check if player is in range of the protected
```suggestion
     * If protecting entity isn't in fight mode yet, check if player is in range of the protected
```
Ich persönlich finde das so verständlicher

2023-05-17 09:41 UTC, JudiTeller commented on game/src/ecs/components/ai/transition/ProtectOnApproach.java
> + * <p>Entity will stay in fight mode once it entered it
```suggestion
 * <p>Entity will stay in fight mode once entered
```

2023-05-17 09:41 UTC, JudiTeller commented on game/src/ecs/components/ai/transition/ProtectOnAttack.java
> + * damage to it. Entity will stay in fight mode
```suggestion
 * Implements an AI that protects a specific entity with a HealthComponent, if the hero dealt damage to it.
 * <p> Entity will stay in fight mode once entered.
```
Um konsistent mit der Javadoc von ProtectOnApproach zu bleiben

2023-05-18 13:16 UTC, AMatutat commented
@cagix Hier ist auch ein Bounty. Ich finds gut und @JudiTeller scheinbar auch. 
Ich müsste das wegen der neuen package struktur (kam zeitlich nach der Abgabe) noch rebasen. 
Aber ansonsten passt.

2023-05-20 13:37 UTC, AMatutat commented on game/test/ecs/components/ai/transition/ProtectOnApproachTest.java
> +    public void testHeroInRange() {
der test scheitert

2023-05-20 14:20 UTC, Pascal378 commented on game/test/ecs/components/ai/transition/ProtectOnApproachTest.java
> +    public void testHeroInRange() {
Ja, das liegt noch daran das es bisher Probleme beim erstellen des Heros während des Testens gab. Sollte aber wohl durch [@664](https://github.com/Programmiermethoden/Dungeon/pull/664) gefixt werden. Andernfalls werde ich den Test erstmal auslassen, bis es eine Möglichkeit gibt den Hero ohne Exception zu erstellen während der Tests.

Ich hänge gerade noch an ein paar anderen Abgaben für die nächste Woche, sobald ich Zeit finde gehe ich alles was hier im PR erwähnt wurde an.

2023-05-20 15:39 UTC, cagix commented
> @cagix Hier ist auch ein Bounty. Ich finds gut und @JudiTeller scheinbar auch. 
> 
> Ich müsste das wegen der neuen package struktur (kam zeitlich nach der Abgabe) noch rebasen. 
> 
> Aber ansonsten passt. 

@Pascal378 welches team sind sie, damit ich mir die bonuspunkte schon mal notieren kann?

2023-05-20 15:42 UTC, Pascal378 commented
> > @cagix Hier ist auch ein Bounty. Ich finds gut und @JudiTeller scheinbar auch.
> > Ich müsste das wegen der neuen package struktur (kam zeitlich nach der Abgabe) noch rebasen.
> > Aber ansonsten passt.
> 
> @Pascal378 welches team sind sie, damit ich mir die bonuspunkte schon mal notieren kann?

Wir sind Team 104, danke

2023-05-26 08:12 UTC, Kushurando commented
Die constructors für ProtectOnAttack haben kein Public vor stehen, das müsste noch rein, sonst gehen die nicht

2023-05-26 08:58 UTC, Pascal378 commented
Hab die Konstruktoren Public gemacht und die Transitions von einander in unterschiedliche PRs ausgelagert.

Der PR für Approach ist jetzt hier zu finden: https://github.com/Programmiermethoden/Dungeon/pull/696

2023-05-26 09:03 UTC, cagix commented
@AMatutat @fwatermann @JudiTeller Der zweite Teil, der ursprünglich hier enthalten war, ist nach #696 ausgelagert worden. Der Split ist im Praktikum besprochen worden.

2023-05-26 09:13 UTC, cagix commented
@AMatutat Der Code läuft natürlich nicht mehr mit der neuen Struktur. Interessanterweise gibt es keine Merge-Konflikte, aber es ist noch ein Refactoring auf die neuen Strukturen notwendig. Das müsste sinnvollerweise einer von uns machen, oder?

2023-06-05 07:11 UTC, AMatutat commented
@Lena241 hier bitte einmal rebasen und refactorn.

2023-06-05 07:40 UTC, cagix commented
@Lena241 @AMatutat Mein Vorschlag wäre, einen Hilfsbranch vom letzten kompatiblen Commit (d.h. den Commit, von dem aus die Studis Anfang April geforkt hatten) aus zu erstellen und diesen PR auf diesen Hilfsbranch umzuzweigen (das Ziel kann man oben per "Edit" anpassen) und zu mergen. Damit kriegen die Studis ihre Bonuspunkte und ihre Autorenschaft ist im Repo. Danach kannst Du den Hilfsbranch intern rebasen und die Sachen auf die neuen Strukturen umstellen und dann per neuem PR in den Master mergen.

2023-06-06 14:02 UTC, merged