[GAME] refactor package structure
Programmiermethoden/Dungeon pull request #657
Opened 2023-05-12 20:50 UTC by AMatutat

Fixes #583.

Für Details bitte #583 aufrufen und anschauen.

Key-Änderungen:
- Aufteilen in `api`, `content` und `starter`
- Einheitlicheres Benennen der Komponenten und Systeme
- `game/test` wurde analog zu `game/src` umstrukturiert

---
Das Ziel war unter anderem, dass das Paket `content` entfernt werden kann und `api` immer noch lauffähig ist. Das ist derzeit jedoch nicht der Fall. 
Damit das Konzept vollständig aufgeht, müssen entweder a) einige Systeme noch einmal gründlich überdacht werden oder b) wir schieben quasi alles nach `api`, und das `content`-Paket verliert an Nutzen.

Ich würde die Klassen dennoch gerne schon in das Paket `content` schieben, als eine Art Markierung dafür, was am Ende dort alles liegen soll.
@cagix: Wenn dir dieser Ansatz passt, würde ich für Variante a ein Issue anlegen und es zeitlich Richtung Projektende schieben.

2023-05-13 08:20 UTC, cagix commented
> Damit das Konzept vollständig aufgeht, müssen entweder a) einige Systeme noch einmal gründlich überdacht werden oder b) wir schieben quasi alles nach api, und das content-Paket verliert an Nutzen.

@AMatutat Kannst Du das bitte mal etwas mehr ausführen? Welche Systeme würdest Du in `content` sehen und was verhindert das im Moment und wie könnte die Überarbeitung aussehen?

2023-05-13 12:01 UTC, AMatutat commented
>  Welche Systeme würdest Du in content sehen

Siehe PR. Ich hab die alle dorthin geschoben. Mein Gedanke war, alles was nicht wirklich eine fundamentale Basisfunktion ist oder zu schwer in der Umsetzung für ein 2. Semester ist, wird nach `content` extrahiert.

> verhindert das im Moment und wie könnte die Überarbeitung aussehen?

Allgemein gesprochen: In meinen Augen fundamentale Systeme verwenden für Edge-Cases Components, welche ich in `content` sehe. 
Das `VelocitySystem` (api) prüft z.B ob nicht grade die Sterb-Animation abgespielt wird, wenn ein `HealthComponent` (content) in der Entität existiert. 

Spontane Idee: Könnte man nicht einfach alle Components bis auf das DrawComponent aus der Entität entfernen, wenn das Ding stirbt? Dann kann die Animation noch zuende abgespielt werden und dann wird das Objekt gelöscht. 

und irgendein Edge-Case mit einem potenziellen `ProjectileComponent` (content) gibt es auch. 


Ich glaube jetzt kommt das hoch, was du und @AHeinisch schon öfters angesprochen habt, ich aber als unproblematisch deklariert habe: Systeme agieren auf mehr als ein Component. Es gibt keine klaren Zuständigkeiten.

2023-05-13 12:03 UTC, AMatutat commented on game/src/api/systems/VelocitySystem.java
> +import content.component.HealthComponent;
hier

2023-05-13 12:03 UTC, AMatutat commented on game/src/api/systems/VelocitySystem.java
> +import content.component.ProjectileComponent;
hier

2023-05-13 12:04 UTC, AMatutat commented on game/src/api/systems/DebuggerSystem.java
> +public class DebuggerSystem extends System {
Der sollte vermutlich eh nach content

2023-05-13 12:05 UTC, AMatutat commented on game/src/api/systems/PlayerSystem.java
> +import content.configuration.KeyboardConfig;
hmm, das hab ich komplett übersehen. 
Muss ich nochmal grübeln.

2023-05-13 12:06 UTC, AMatutat commented on game/src/api/components/AIComponent.java
> +import content.utils.componentUtils.aiComponent.fight.CollideAI;
Hier müsste man die default werte nochmal überarbeiten

2023-05-13 12:06 UTC, AMatutat commented on game/src/api/Game.java
> +import content.systems.HealthSystem;
der kram erledigt sich mit #582

2023-05-13 12:07 UTC, AMatutat reviewed
Hab nochmal rübergeguckt und diese Klassen importieren irgendwas von content

2023-05-13 12:13 UTC, AMatutat commented
mäp ich sehe grade, ich hab nach den experimentieren meinen Head ein wenig zu weit nach hinten verschoben... Muss ein paar utils noch verschieben

2023-05-13 12:29 UTC, AMatutat commented
@cagix 
Ich hab jetzt mal die `api` deutlich mehr auf die minimalen Basics runtergebrochen. 
Auf ECS ebene bedeutet das: 
- `DrawSystem`
- `PositionSystem`
- `VelocitySystem`
- + entsprechende Components

=> Die `api` erlaubt es dir, irgendwas irgendwo hinzusetzen, das Ding rumrennen zu lassen und es zu zeichnen. Mehr nicht. 

Mit #555 würde noch ein `CameraSystem` zur `api` kommen. 

Alles ander ist `content`. 
Führt auch dazu, dass eigentlich nur das `VelocitySystem` noch auf content zugreift, und das sollte man einfach umbesinnen können. Siehe vorschlage oben,

2023-05-13 12:30 UTC, AMatutat commented on game/src/api/components/AIComponent.java
> +import content.utils.componentUtils.aiComponent.fight.CollideAI;
alternative: AI ist content

2023-05-13 12:31 UTC, AMatutat commented on game/src/api/systems/PlayerSystem.java
> +import content.configuration.KeyboardConfig;
Im neuen Entwurf ist das alles content, in der api sollten keine expliziten Tastendrücke implementiert sein

2023-05-13 12:31 UTC, AMatutat commented on game/src/api/systems/DebuggerSystem.java
> +public class DebuggerSystem extends System {
im neuen Vorschlag ist das Ding content

2023-05-13 12:35 UTC, AMatutat commented
@cagix wenn wir schon am schieben sind, sollte alles was Projektbezogen ist, auch in einen top level package verschoben werden?
Dann wäre api das rudimentäre Framework für PM + content mit ein paar Bonus Features.
In `teachingDungeon` (besserer name muss her) liegt dann der Quiz/Quest kram.
Oder den kram direkt in das `ddl-connector` Projekt?

2023-05-13 12:37 UTC, cagix commented
> @cagix Ich hab jetzt mal die `api` deutlich mehr auf die minimalen Basics runtergebrochen. Auf ECS ebene bedeutet das:
> 
> * `DrawSystem`
> * `PositionSystem`
> * `VelocitySystem`
> * * entsprechende Components

Ich würde noch die Tastatursteuerung (`PlayableComponent` plus das passende System?) in der API sehen. Anderenfalls müsste man das auch immer selbst implementieren.



> => Die `api` erlaubt es dir, irgendwas irgendwo hinzusetzen, das Ding rumrennen zu lassen und es zu zeichnen. Mehr nicht.

Jupp. Ich hatte gefragt, weil ich so Sachen wie "AI" nicht als Core-API sehen würde. Aber jetzt ist das ja auch wech ..

> 
> Mit #555 würde noch ein `CameraSystem` zur `api` kommen.

Klingt sinnvoll.

> 
> Alles ander ist `content`. Führt auch dazu, dass eigentlich nur das `VelocitySystem` noch auf content zugreift, und das sollte man einfach umbesinnen können. Siehe vorschlage oben,

Das scheint mir ein grundsätzliches Problem am ECS zu sein. Was machen denn andere? 

Wenn ein System immer nur auf "seine" Components zugreifen darf, dann schränkt man sich ziemlich schnell ziemlich ein. 

Wenn es aber quasi alle Freiheiten beim Zugriff gibt, bekommt man schnell alle möglichen Probleme (welche Animation wird nun genau abgespielt bzw. wer darf wann was setzen bzw. in welcher Reihenfolge sollte wer was setzen).

2023-05-13 12:40 UTC, cagix commented
@AMatutat Mir ist grad noch ne Idee für die Namen gekommen: `core` (statt `api`) und `contrib` (statt `content`). Ist angelehnt an die Debian-Repo-Namen.

2023-05-13 12:42 UTC, AMatutat commented
> Ich würde noch die Tastatursteuerung (PlayableComponent plus das passende System?) in der API sehen. Anderenfalls müsste man das auch immer selbst implementieren.

Hab ich auch erst gedacht, aber grade dieses System wirst du immer wieder erweitern wollen. Dein Held kann jetzt Springen? Das musst du ja irgendwie da hinterlegen. 
Man könnte es evtl umbauen und eine Art Map mit `<Key,Function>` in den Ding speichern und dann per `add`-Methode neue Funktionen hinzufügen. 

Hmm find ich gar nicht schlecht.

2023-05-13 12:47 UTC, cagix commented
> @cagix wenn wir schon am schieben sind, sollte alles was Projektbezogen ist, auch in einen top level package verschoben werden? Dann wäre api das rudimentäre Framework für PM + content mit ein paar Bonus Features. In `teachingDungeon` (besserer name muss her) liegt dann der Quiz/Quest kram. Oder den kram direkt in das `dsl-connector` Projekt?
> 
> Die Annotationen für die DSL würden natürlich bleiben

ufff. gute frage.

im `game`-projekt sehe ich das nicht, das hat mit dem dungeon-framework nix zu tun. 

aber `dsl-connector` ist das auch nicht. vielleicht wird es zeit für ein weiteres gradle-projekt?

2023-05-13 12:50 UTC, AMatutat commented
> > Alles ander ist content. Führt auch dazu, dass eigentlich nur das VelocitySystem noch auf content zugreift, und das sollte man einfach umbesinnen können. Siehe vorschlage oben,

> Das scheint mir ein grundsätzliches Problem am ECS zu sein. Was machen denn andere?

Ist irgendwie auch die große Frage für #499 . Mein Eindruck ist, jeder macht irgendwie was er will. Gibt Projekte die eine starke Trennung forcieren und dann mit (in meinen Augen wirren) Konstrukten Arbeiten, um irgendwelche Infos abzulegen und von jemanden anderen bearbeiten zu lassen. Andere Projekte schienen mir da wieder mehr in unsere Richtung zu gehen. 

Wir haben natürlich den Sonderfall, dass wir nicht ein Spiel sind sondern ein Framework+. 
@AHeinisch Deine Einschätzung? 

> Wenn ein System immer nur auf "seine" Components zugreifen darf, dann schränkt man sich ziemlich schnell ziemlich ein.

Entweder das, oder die Implementierung wird richtig unschön, weil du dauernd irgendwo irgendwelche Flags setzten und anschauen würdest. 


> Wenn es aber quasi alle Freiheiten beim Zugriff gibt, bekommt man schnell alle möglichen Probleme (welche Animation wird nun genau abgespielt bzw. wer darf wann was setzen bzw. in welcher Reihenfolge sollte wer was setzen).

Vielleicht wäre die Regel: Gucken aber nicht anfassen sinnvoll. Müsste ich aber durchdenken. Dann dürfte ein System nur Werte zum direkt zugehörigen Component ändern. 
Auf der anderen Seite ist das auch irgendwie murks, dann müsste das VelocitySystem irgendwo aufschreiben, dass doch mal bitte jemand die Position der Entität ändert. 

> wer darf wann was setzen bzw. in welcher Reihenfolge sollte wer was setzen).

Für das Problem hatte ich mal #244 angelegt. Bisher war es halt nie sonderlich problematisch

2023-05-13 12:52 UTC, AMatutat commented
> aber dsl-connector ist das auch nicht. vielleicht wird es zeit für ein weiteres gradle-projekt?

auch denkbar.

2023-05-13 17:36 UTC, cagix commented
> > aber dsl-connector ist das auch nicht. vielleicht wird es zeit für ein weiteres gradle-projekt?
> 
> 
> 
> auch denkbar. 
> 
> 
> 
> 
> 
> Edit: GItHub es wird endlich Zeit für richtige Threads auch in Kommentaren. Ist ja wirr... 

das schräge ist dabei, dass es das in "discussions" gibt und du discussions in tickets konvertieren/verschieben kannst und umgedreht...

2023-05-13 17:40 UTC, cagix commented
> > > Alles ander ist content. Führt auch dazu, dass eigentlich nur das VelocitySystem noch auf content zugreift, und das sollte man einfach umbesinnen können. Siehe vorschlage oben,
> 
> 
> 
> > Das scheint mir ein grundsätzliches Problem am ECS zu sein. Was machen denn andere?
> 
> 
> 
> Ist irgendwie auch die große Frage für #499 . Mein Eindruck ist, jeder macht irgendwie was er will. Gibt Projekte die eine starke Trennung forcieren und dann mit (in meinen Augen wirren) Konstrukten Arbeiten, um irgendwelche Infos abzulegen und von jemanden anderen bearbeiten zu lassen. Andere Projekte schienen mir da wieder mehr in unsere Richtung zu gehen. 
> 
> 
> 
> Wir haben natürlich den Sonderfall, dass wir nicht ein Spiel sind sondern ein Framework+. 
> 
> @AHeinisch Deine Einschätzung? 
> 
> 
> 
> > Wenn ein System immer nur auf "seine" Components zugreifen darf, dann schränkt man sich ziemlich schnell ziemlich ein.
> 
> 
> 
> Entweder das, oder die Implementierung wird richtig unschön, weil du dauernd irgendwo irgendwelche Flags setzten und anschauen würdest. 
> 
> 
> 
> 
> 
> > Wenn es aber quasi alle Freiheiten beim Zugriff gibt, bekommt man schnell alle möglichen Probleme (welche Animation wird nun genau abgespielt bzw. wer darf wann was setzen bzw. in welcher Reihenfolge sollte wer was setzen).
> 
> 
> 
> Vielleicht wäre die Regel: Gucken aber nicht anfassen sinnvoll. Müsste ich aber durchdenken. Dann dürfte ein System nur Werte zum direkt zugehörigen Component ändern. 
> 
> Auf der anderen Seite ist das auch irgendwie murks, dann müsste das VelocitySystem irgendwo aufschreiben, dass doch mal bitte jemand die Position der Entität ändert. 
> 
> 
> 
> > wer darf wann was setzen bzw. in welcher Reihenfolge sollte wer was setzen).
> 
> 
> 
> Für das Problem hatte ich mal #244 angelegt. Bisher war es halt nie sonderlich problematisch

ne ganz blöde idee: die systems könnten auf den components arbeiten (lesend) und ihre ergebnisse (neue werte oder components oder was auch immer) in eine art message-queue einspeisen. wenn alle systems durch sind, könnte man die queue nach bestimmten regeln reduzieren und dann auf die entitäten anwenden.

2023-05-14 17:03 UTC, AHeinisch commented
Threads oder so wären schön. Also wenn ich das richtig sehe, soll ich hier eine Antwort geben für:

<details>
  <summary>wie andere ECS Strukturen der Packages/Ordner machen?</summary>
  
  Variante A: (Normale Struktur für kleine ECS/Mittelgroße nutzen die meisten Devs für POCs oder Game Jams) 

  ```
root
|
├─ Compontens
|  ├─ PositionComponent
|  ├─ AnimationComponent
|  └─ VelocityComponent
|
├─ Systems
|  ├─ PositonSystem
|  ├─ AnimationSystem
|  └─ VelocitySystem
|
├─ Game
├─ Launcher
└─ ... basecode (Filehandling etc.)
```

Variante B: (Feature basierte Struktur für mittlere bis größere) 
```
root
|
├─ Movement
|  ├─ Components
|  |  ├─ PositionComponent
|  |  └─ VelocityComponent
|  ├─ Systems
|  |  ├─ PositonSystem
|  |  └─ VelocitySystem
|  └─ Helper
|     └─ VelocitySystem 
├─ Drawing
|  ├─ Components
|  |  └─  AnimationComponent
|  ├─ Systems
|  |   └─ AnimationSystem
|  └─ Helper
|     └─ TextureHandler
├─ Game
├─ Launcher
└─ ... basecode (Filehandling etc.)
```
Variante C: (Erweiterung von B)
Jedes Feature ist eine eigene Bibliothek, die auf anderen Bibliotheken basiert. Dadurch kann ein Graph von der Basisbibliothek entstehen (Grundfeatures wie z.b. ECS registrieren von Systemen bzw. Entitäten).


Kurz, was ich meistgelesen hatte:
Variante A ist am einfachsten zum Beginn, wo noch keine Struktur oder eine sich schnell ändernde Struktur existiert.
Variante B wird dann aus der Variante A entwickelt und dabei die Komponenten bzw. Systeme aufgeräumt.
Variante C wird benutzt, sobald Variante B stabil ist und auch die Compiler Zeit langsam ein Problem wird. Sowie kleinere, übersichtlichere Projekte.

</details>

<details>
  <summary>zugriff auf Komponenten</summary>

Also erstmal ECS gibt es mittlerweile in mehreren Varianten:

<details>
<summary>Preview für #499 </summary>
Es gibt halt X Varianten der Architektur
Grund Unterscheidung reines ECS (Komponente sind nur Daten) und nicht reines ECS (Komponente können auch Referenzen enthalten) 

1 .Traditionelle ECS → Entitäten sind nur Sammlungen von Komponenten, welche nur eine Sammlung von Daten sind. Systeme arbeiten auf den Entitäten und deren dazugehörigen Komponenten. Systeme sind die einzigen die auf Entitäten oder Komponenten zugreifen dürfen( z.b. PositionSystem darf E1 die Position ändern aber E2 darf nicht die von E2 ändern). Ein System ist also so geschrieben das der Code nicht "verändert" werden muss. Eigentlich immer rein
2. Hybride ECS → irgendwie 2 Definitionen welche sich unterscheiden 
 1. Hybrid im Sinne von Traditionelles ECS und die Komponenten enthalten Referenzen z.b. StrategyPattern
 2. Hybrid im Sinne von OOP mit Vererbung der "Entität" z.b. Godot alle Komponenten sind von Node abgeleitet und bilden dann einen Vererbungsbaum [Label](https://docs.godotengine.org/en/stable/classes/class_label.html#label)
Inherits: [Control](https://docs.godotengine.org/en/stable/classes/class_control.html#class-control) < [CanvasItem](https://docs.godotengine.org/en/stable/classes/class_canvasitem.html#class-canvasitem) < [Node](https://docs.godotengine.org/en/stable/classes/class_node.html#class-node) < [Object](https://docs.godotengine.org/en/stable/classes/class_object.html#class-object)
3. Reactive ECS → nutzen wir jetzt nicht, die Entitäten sind Streams von Events und das Verhalten sowie Daten sind in einer Komponente abgelegt. Das gesamte Verhalten liegt immer als Funktion in der Komponente.
4. Data-Driven ECS → Entitäten haben Daten (Komponenten). Systeme dürfen wie immer als einzige die Entitäten oder Daten anpassen. Das Verhalten wiederum ergibt sich aus den Daten.  Z.b. Bei einer Entität hat sich die Position geändert, daher wird diese bei der nächsten Iteration beachtet. Eine Entität, wo es keine Änderung gab, wird bei der nächsten Iteration ignoriert. Anwendung z.b. bei |Dialogue System for Unity](https://assetstore.unity.com/packages/tools/ai/dialogue-system-for-unity-11672)
5. Entity System Framework (ESF) → Ein ECS für ein ECS. Abstraktion eines ECSs in die Funktionalität welche ein ECS möglich macht. Die unterschiedlichen Arten eines Systems als Vorlage oder eine Basis Entität, welche in den meisten Fällen ausreicht. Beispiel [libgdx/ashley](https://github.com/libgdx/ashley)

Es gibt noch viel mehr Abweichungen aber wir befinden uns wohl eher bei 
</details>

Wir dürfen nicht einschränken, dass nur ein System auf einer Komponente arbeitet. Eigentlich ist ein System genau für eine Sache zuständig. Z.b. Darstellen im Spiel(Drawsystem), Lebenspunkte reduzieren(HealthSystem), Bewegen im Spiel (VelocitySystem)

Vielleicht sind wir nicht immer eindeutig mit, was unser System wirklich macht und ob dies nicht vielleicht zu viel ist. Ggfls bietet sich eine Aufsplittung an



</details>

2023-05-14 17:59 UTC, cagix commented
im prinzip entspricht das dem vorschlag von @AMatutat und mir - es gibt `systems` und `components` und `utils` als hauptgliederung ...

wir sind mittlerweile recht groß - vielleicht sollten wir direkt mal über (b) nachdenken? @AMatutat was denkst du? das würde dann vielleicht die angedachten `core` und `contrib` ersetzen, damit die strukturen nicht zu tief werden?


zugriff systems auf components: vermutlich ist das so; und selbst, wenn wir es wollten, könnten wir das ja auch gar nicht beschränken... einen vorschlag hatte ich oben gemacht ("message-queues"). den von @AHeinisch sollten wir dringend diskutieren - der zuschnitt der systeme ist gefühlt schritt-um-schritt gewachsen und könnte recht gut suboptimal sein ....

2023-05-14 20:47 UTC, AMatutat commented
Modul für das Projekt ist angelegt. Hab es mal "dungeon" genannt. 
Inhalte vollständig extrahieren dann in #661

2023-05-14 21:23 UTC, AMatutat commented on gradle.properties
> +  --add-exports jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED \
ich weiß nicht so richtig warum aber scheinbar hat das was mit unseren package Namen zu tun....

2023-05-14 21:25 UTC, AMatutat commented
so @cagix das wäre meine aktuelle wünsch Vorstellung.
Finale Entscheidung liegt bei dir. 

---
Für aufbekommende non package related Diskussionen habe ich Issues angelegt. Die gehen also nicht verloren

2023-05-15 08:41 UTC, cagix requested changes
@AMatutat Ich denke, damit kann man arbeiten.

Die Packages sind nicht einheitlich benannt: In `src` ist es oft Singular (bis auf `contrib.systems`), in `test` immer Plural. Meine Empfehlung wäre, auch in `src` immer die Pluralform zu nutzen.
 
- [x] `contrib.component` => `contrib.components` (src)
- [x] `contrib.entity` => `contrib.entities` (src) 
- [x] `contrib.utils.componentUtils` => `contrib.utils.components` (src, test)
- [x] `core.utils.componentUtils` => `core.utils.components` (src, test)


Fünf zusätzliche Fragen:

- Sollte `dsl-connector` noch mit `dungeon` verheiratet werden? Die Klassen in `dsl-connector` kann man genau wie das Zeugs in `dungeon` nur zusammen mit `game` und `dsl` nutzen. => Ich würde alles unter `dsl-connector` nach `dungeon` schieben.
- Ist `PlayerComponent` wirklich `contrib`? Mir scheint, dass ist eine lebensnotwendige Basis, um überhaupt was bewegen zu können?
- Brauchen wir in `contrib.utils` noch ein Unterpackage `componentUtils`? Es ist das einzige Unterpackage in `contrib.utils`, und alles in `componentUtils` trägt zudem noch den Zusatz `*Component`? Oder sollte es dann nur `components` heißen (in `core.utils` gibt es noch `controller` (ohne Zusatz `*Utils`))?
- Der HUD passt irgendwie nicht unter Utils? Sollte der direkt in `core` liegen?
- Brauchen wir `test/testingUtils/` wirklich?

2023-05-15 08:52 UTC, AMatutat commented
> Sollte dsl-connector noch mit dungeon verheiratet werden? Die Klassen in dsl-connector kann man genau wie das Zeugs in dungeon nur zusammen mit game und dsl nutzen. => Ich würde alles unter dsl-connector nach dungeon schieben.

können wir machen. 

> Ist PlayerComponent wirklich contrib? Mir scheint, dass ist eine lebensnotwendige Basis, um überhaupt was bewegen zu können?

Mit Hinblick auf #658 sollte es nach core, yes.

> Brauchen wir in contrib.utils noch ein Unterpackage componentUtils? Es ist das einzige Unterpackage in contrib.utils, und alles in componentUtils trägt zudem noch den Zusatz *Component? Oder sollte es dann nur components heißen

Ich wollte es symmetrisch zu `core` halten. 
Vielleicht wäre `utils.components.ai` am besten, oder?  

>  (in core.utils gibt es noch controller (ohne Zusatz *Utils))?

Sind ja auch die Controller selbst (welche Utils sind). Fliegen mit #550 eh raus. 

> Der HUD passt irgendwie nicht unter Utils? Sollte der direkt in core liegen?

Können wir machen. Ich sehe beides, hab keine Präferenz. 

> Brauchen wir test/testingUtils/ wirklich?

Da liegt irgendeine Counter drinnen und ich müsste erst gucken warum der dort ist. Ist nicht so richtig Scope von diesem PR:

2023-05-15 09:02 UTC, cagix commented
> Vielleicht wäre utils.components.ai am besten, oder?

ja

2023-05-15 09:05 UTC, cagix commented
> > > Brauchen wir test/testingUtils/ wirklich?
> > 
> > 
> > Da liegt irgendeine Counter drinnen und ich müsste erst gucken warum der dort ist. Ist nicht so richtig Scope von diesem PR:
> 
> Der kommt leider von mir, da ich den AtomicInteger nicht für Testen von den Strategien nutzen wollte. Dennoch würde es, glaube ich, mehr Sinn machen den AtomicInteger zu nutzen anstelle von so einer eigenen "Zähler" Klasse, welche den Aufruf zählt. Ich wollte nur noch Mocking einbauen, wenn es nicht anders geht.

@AHeinisch Ich finde die Klasse nicht "schlimm" oder so - ich hatte mich nur gewundert, dass es ein Package mit einer so mutterseelenalleinstehenden Klasse gibt. Das ist für mich vergleichbar mit einer Gliederung in einer schriftlichen Arbeit, wo es nur eine H3-Überschrift unter einer H2-Überschrift gibt - ein Gliederungsproblem. 

Kannst ja überlegen, ob Du das irgendwie anders ohne diese Hilfsklasse lösen kannst. Aber ich stimme Dir zu: Mocking nur, wenn es anders nicht geht oder extrem aufwändig wird.

2023-05-15 09:11 UTC, AMatutat commented
@cagix so?


PS: ich knall nach den Berge direkt die beiden PRs für #663 hinterher. Also noch nicht schlafen gehen. :P

2023-05-15 09:19 UTC, cagix commented
> @cagix so?
> 
> PS: ich knall nach den merge direkt die beiden PRs für #663 hinterher. Also noch nicht schlafen gehen. :P

ich hab wieder praktikum - d.h. ich bin dann erst heute abend wieder da.

2023-05-15 09:21 UTC, AMatutat commented
> ich hab wieder praktikum - d.h. ich bin dann erst heute abend wieder da. 


Args... naja muss ich mit leben.

2023-05-15 09:22 UTC, cagix approved these changes
go for it!

mit `testingUtils` bin ich noch nicht so richtig glücklich, aber das kann separat behoben werden. die klasse `SimpleCounter` ist ja relativ simple (harhar) und könnte möglicherweise on-the-fly in den tests formuliert werden?

2023-05-15 09:25 UTC, merged