[GAME] remove SkillComponent and SkillSystem
Programmiermethoden/Dungeon pull request #672
Opened 2023-05-17 07:38 UTC by Lena241

fixes #602 

Der Cool Down ist direkt in Skill implementiert
- SkillSystem komplett entfernt, da die einzige Aufgabe das runterzählen des Cool Downs war
- benutzt die Systemzeit und ist nicht mehr frameabhängig
- der Feuerball kann nach Ablauf des Cool Downs wieder benutzt werden

2023-05-17 09:52 UTC, AMatutat commented on game/src/contrib/components/SkillComponent.java
braucht es das SkillComponent dann eigentlich noch?

2023-05-17 09:53 UTC, AMatutat requested changes

2023-05-17 09:53 UTC, AMatutat commented on game/test/contrib/systems/SkillSystemTest.java
ohne System braucht es auch keine Tests mehr

2023-05-17 10:24 UTC, Lena241 commented on game/test/contrib/systems/SkillSystemTest.java
Tests sind ein eigener Branch, deshalb habe ich das hier übersehen. 
Ich habe jetzt ein bisschen was rausgeschmissen. Finale Überarbeitung dann im eigenen PR.

2023-05-24 07:02 UTC, AMatutat commented on game/src/contrib/utils/components/skill/Skill.java
> +    public boolean canBeUsedAgain() {
can be private?

2023-05-24 07:05 UTC, AMatutat commented on game/src/contrib/utils/components/skill/Skill.java
>      public void execute(Entity entity) {
javadoc

```
/**
 * Executes the logic of the skill if it is not currently on cooldown.
 * <p>If the skill was used, the cooldown will be set.</p>
 */
```

2023-05-24 07:05 UTC, AMatutat requested changes
klein kram

2023-05-24 07:16 UTC, AMatutat approved these changes
lgtm

2023-05-24 07:20 UTC, merged