[GAME] CameraComponent & CameraSystem
Programmiermethoden/Dungeon pull request #699
Opened 2023-05-31 08:13 UTC by Lena241

fixes #555 

- DungeonCamera entfernt und stattdessen CameraSystem und CameraComponent erstellt
- Die Kamera fokusiert auf den Hero und wenn dieser nicht existiert, auf die StartTile des Levels
    - Level ist auch sichtbar wenn kein Hero existiert; vorher konnte das Level außerhalb des Blickfeldes sein

TODO:
- [ ] Javadoc
- [ ] Tests

2023-06-05 07:17 UTC, AMatutat commented on game/src/contrib/entities/EntityFactory.java
> +        new CameraComponent(hero);
link das oben auch in der javadoc wie die anderen components

2023-06-05 07:20 UTC, AMatutat reviewed
code sieht gut aus

2023-06-06 11:24 UTC, AMatutat submitted a review, later dismissed

2023-06-06 11:31 UTC, AHeinisch commented on build.gradle
> +    testImplementation 'org.junit.jupiter:junit-jupiter:5.8.1'
@AMatutat gewollte Änderung?

2023-06-06 11:32 UTC, Lena241 commented on build.gradle
> +    testImplementation 'org.junit.jupiter:junit-jupiter:5.8.1'
Nein, habe mich verklickt und nicht aufgepasst. Wird gleich geändert.

2023-06-06 11:38 UTC, AMatutat commented on game/test/core/systems/CameraSystemTest.java
> +        CameraComponent cameraComponent = new CameraComponent(entity);
```suggestion
new CameraComponent(entity);
```

2023-06-06 11:42 UTC, AMatutat requested changes
ist auf mein mist gewachsen, i know aber jetzt will ich anderen mist

2023-06-06 12:23 UTC, AMatutat approved these changes

2023-06-06 12:23 UTC, merged