[Doc/Publication] add overview table of conferences
Programmiermethoden/Dungeon pull request #732
Opened 2023-06-12 08:37 UTC by AMatutat

fixes #431

Dieser PR fügt eine Übersichtstabelle der in #431 genannten Konferenzen hinzu.
Unter dem "Bereich"-Abschnitt habe ich versucht, eine grobe Übersicht über die Themen zu geben, die auf der Konferenz behandelt werden. Diese können von Jahr zu Jahr variieren und sollten daher als grobe Kategorisierung verstanden werden.
Um den Zyklus zu bestimmen, habe ich mich auf die Informationen auf der Webseite verlassen und kurz recherchiert, ob es in den vergangenen Jahren ebenfalls Konferenzen gab, um den Zyklus festzulegen.

2023-06-12 16:04 UTC, cagix reviewed
Die SIGCSE (https://cssplice.github.io/SIGCSE23/CFP.html) fehlt noch, oder? 

Inhaltlich stelle ich mir grad die Frage, ob wir Autograder hier im Dungeon-Repo mit aufnehmen wollen oder ob das nicht was für das D2G-Repo ist? Oder liegt das alles so nah beisammen, dass man im D2G-Repo beispielsweise auch einige der SE-Tagungen auflisten würde? Wäre es dann evtl. eine Lösung, im D2G-Repo in `docs/related-work/conferences.md` einfach nur auf dieses Markdown-File zu verlinken?

@AMatutat @AKirsch1 Meinungen?

2023-06-12 16:35 UTC, AMatutat commented
> Die SIGCSE (https://cssplice.github.io/SIGCSE23/CFP.html) fehlt noch, oder?

Ha die hatte ich rausgeworfen, weil der Link heute Mittag tot war. Wohl nur ein temporärer fehler

2023-06-12 16:37 UTC, AMatutat commented
> Inhaltlich stelle ich mir grad die Frage, ob wir Autograder hier im Dungeon-Repo mit aufnehmen wollen oder ob das nicht was für das D2G-Repo ist? Oder liegt das alles so nah beisammen, dass man im D2G-Repo beispielsweise auch einige der SE-Tagungen auflisten würde? Wäre es dann evtl. eine Lösung, im D2G-Repo in docs/related-work/conferences.md einfach nur auf dieses Markdown-File zu verlinken?

Ich krieg etwas Bauchweh bei der "Dezentralisierung". Dann lieber ein Link.

2023-06-13 07:26 UTC, AMatutat commented on doc/related_work/conferences.md
> +| Name | Bereich | Zyklus | Link |
hab ich mal mit Prettier gemacht.... sieht seltsam aus

2023-06-13 11:31 UTC, cagix requested changes
fast da :)

2023-06-13 11:31 UTC, cagix commented on doc/related_work/readme.md
> +title: "Startseite related work "
```suggestion
title: "Startseite related work"
```

2023-06-13 11:31 UTC, cagix commented on doc/related_work/readme.md
> +Auch eine Übersicht mit verschiedenen [Konferenzen](conferences.md) wird gepflegt.
```suggestion
Auch eine Übersicht mit verschiedenen [Konferenzen](conferences.md) wird gepflegt.

```

2023-06-13 11:31 UTC, cagix commented on doc/related_work/conferences.md
mach mal bitte in der spalte "link" noch die nackten links als linktext rein. sonst taucht in jeder zeile der text "link" auf, was optisch nicht so hilfreich ist.

2023-06-14 08:37 UTC, cagix approved these changes
👍

2023-06-14 08:53 UTC, merged