[Doc] add related work Dungeon
Programmiermethoden/Dungeon pull request #733
Opened 2023-06-12 09:14 UTC by AMatutat

bzgl https://github.com/Programmiermethoden/2022-freiraum-dungeon/issues/166

Dieser PR fügt grobe Zusammenfassungen und Einordnungen anderer Arbeiten in die Dokumentation hinzu. 
Dabei habe ich mich vor allem auf Arbeiten direkt mit dem Fokus Gamification konzentriert. 

Die Zusammenfassungen sind teilweise noch recht knapp (oder fehlen). Ich würde das Ganze trotzdem gerne mergen und dann nach und nach ergänzen. So können die jetzigen Schwierigkeiten schon einmal festgehalten werden, und neue Ergebnisse werden einfacher integriert.

2023-06-12 16:06 UTC, cagix commented
@AMatutat Vorgehen passt. Aber ist dann wirklich "fixes ..." korrekt, d.h. muss dann nicht ein Issue offen bleiben, um die bereits bekannten Sachen einzupflegen?

2023-06-12 16:20 UTC, cagix reviewed
@AMatutat Im Prinzip habe ich mir das so vorgestellt.

Die Unterebene "dungeon/" fand ich etwas überraschend. Das würde voraussetzen, dass wir auch noch was zur "dsl/" bekommen? Realistischerweise würde ich die Unterteilung eher weglassen.

Wo ich mir bis jetzt keine Gedanken gemacht hatte, ist das Format. Der Einsatz von YAML-Headern könnte funktionieren, sieht aber in der Vorschau immer etwas hässlich aus (gerade bei längeren Einträgen). Ich würde mal folgende Idee zur Diskussion stellen:

```markdown
---
title: "Titel des Papers oder des Projekts"
---

## Meta-Daten

- title: Titel des Projekts
- author: S. Name and B. Hinz and C. Schulz
- url: Link
- urldate: 2022-12-29
- note: Sonstige Angaben (etwa "Projekt DigiKompASS")

## Zusammenfassung

Kernerkenntnisse. Am besten so, dass man das direkt in ein Paper kopieren könnte.
```

@AKirsch1 Was denkst Du? 

Eventuell statt der Aufzählung eine Tabelle? 

```markdown
|         |                                               |
|---------|-----------------------------------------------|
| title   | Titel des Projekts                            |
| author  | S. Name and B. Hinz and C. Schulz             |
| url     | Link                                          |
| urldate | 2022-12-29                                    |
| note    | Sonstige Angaben (etwa "Projekt DigiKompASS") |
```

Dabei würde ich direkt die Felder aus dem Bibtex benutzen (welches hier noch fehlt btw. ... JabRef ist ein nettes Java-Tool zum Anlegen einer solchen Datei :)

2023-06-13 07:42 UTC, AKirsch1 commented
Wäre es nicht sinnvoller, das direkt als Bibtex-Eintrag als Codeblock einzutragen. Ich finde, der ist genauso gut lesbar wie eine Tabelle oder Liste und kann direkt dahin übernommen werden, wo wir ihn brauchen.

2023-06-13 07:55 UTC, cagix commented
> Wäre es nicht sinnvoller, das direkt als Bibtex-Eintrag als Codeblock einzutragen. Ich finde, der ist genauso gut lesbar wie eine Tabelle oder Liste und kann direkt dahin übernommen werden, wo wir ihn brauchen.

Finde ich super!

Alternativ könnte man auch überlegen, direkt ein Bibtex-File zu pflegen (statt der einzelnen Markdowns) und die Zusammenfassung als Eintrag im Feld `notes`. Aber das ist unübersichtlicher, sowohl in Bezug auf die Notes als auch den Überblick über das related work.

2023-06-13 07:56 UTC, cagix commented
@AMatutat Hier mal ein Beispiel aus PM: https://github.com/Programmiermethoden/PM-Lecture/blob/master/pm.bib

2023-06-13 08:46 UTC, AMatutat commented
Ich hab die bibkeys die bereits vorhanden waren aus dem Projekt-Repo kopiert

2023-06-13 11:27 UTC, cagix requested changes
könnte so gehen. ein paar flüchtigkeitssachen anbei.

@AMatutat das würde an lesbarkeit/nutzbarkeit noch gewinnen, wenn du die bibtex-schnipsel alle in eine datei werfen und diese flink mit jabref formatieren würdest und die schnipsel dann wieder zurück kopieren würdest. oder vielleicht kann das @AKirsch1 mit übernehmen?

2023-06-13 11:27 UTC, cagix commented on doc/related_work/analysis _framework.md
> +## Bibkey
```suggestion
## Bibtex
```

2023-06-13 11:27 UTC, cagix commented on doc/related_work/car_game_mechanical_engineering.md
> +## Bibkey
```suggestion
## Bibtex
```

2023-06-13 11:27 UTC, cagix commented on doc/related_work/digi_komp_ass _escape_room.md
> +## Bibkey
```suggestion
## Bibtex
```

2023-06-13 11:27 UTC, cagix commented on doc/related_work/analysis _framework.md
leerzeichen im dateinamen?

2023-06-13 11:27 UTC, cagix commented on doc/related_work/mapping_task_types_and_gameplay_categories.md
> +link: "https://hal.science/hal-04093538/document"
hier ist noch mehr als nur title?

2023-06-14 08:10 UTC, AMatutat commented
> @AMatutat das würde an lesbarkeit/nutzbarkeit noch gewinnen, wenn du die bibtex-schnipsel alle in eine datei werfen und diese flink mit jabref formatieren würdest und die schnipsel dann wieder zurück kopieren würdest. oder vielleicht kann das @AKirsch1 mit übernehmen?

Wir haben sonst auch noch die "große" bibtex-Datei im Projekt-Repo, theoretisch könnte man diese auch als großes Sammel-Ding hier reinwerfen

2023-06-14 08:33 UTC, cagix commented
> > @AMatutat das würde an lesbarkeit/nutzbarkeit noch gewinnen, wenn du die bibtex-schnipsel alle in eine datei werfen und diese flink mit jabref formatieren würdest und die schnipsel dann wieder zurück kopieren würdest. oder vielleicht kann das @AKirsch1 mit übernehmen?
> 
> Wir haben sonst auch noch die "große" bibtex-Datei im Projekt-Repo, theoretisch könnte man diese auch als großes Sammel-Ding hier reinwerfen

ja, das war initial mein gedanke. beisst sich aber mit der idee, zu jeder arbeit nochmal was einzeln aufzuschreiben. aus meiner sicht gibt es drei optionen:

(a) zu jeder arbeit eine markdown-datei pflegen mit dem bibtex-schnipsel und etwas text
(b) alle arbeiten in einer gemeinsamen bibtex-datei pflegen und die erklärung jeweils in einem `note`-feld
(c) wie (a) plus eine gemeinsame bibtex

option (a) ist übersichtlich und funktioniert auch im browser sehr gut. für das schreiben von paper muss man sich die relevanten bibtex-schnipsel halt zusammenkopieren.

option (b) ist die mit dem wenigsten arbeitsaufwand, wenn man ans paper-schreiben denkt. aber sie ist auch eher unübersichtlich und das `note`-feld ist jetzt auch nicht soooo toll für mehr als einen stichpunkt.

option (c) bringt übersicht und wenig arbeitsaufwand beim paper-erstellen, aber man muss jetzt immer zwei quellen (markdown und bibtex) gleichzeitig pflegen. würde ich deshalb eher nicht machen.

man könnte sich noch (c^') überlegen, wo im markdown der bibtex-eintrag fehlt und stattdessen der bibtex-key aus dem bibtex-file genutzt wird. das würde die doppelung auflösen, ist aber am ende irgendwie auch nicht mehr wirklich übersichtlich für meinen geschmack.

2023-06-14 15:13 UTC, cagix approved these changes

2023-06-14 15:26 UTC, merged