[Doc] dokumentiere Austausch mit Projekt-Teams
Programmiermethoden/Dungeon pull request #772
Opened 2023-06-21 08:42 UTC by AMatutat

fixes #767 
- Fügt **eine** Datei mit groben Zusammenfassungen der Projekte der anderen Teams ein. 

Den CodeHarbor Beitrag habe ich aus der Mail kopiert. Die haben das sehr schön ausführlich formuliert.

Ich habe bewusst auf konkrete Ansprechpartner und Kontaktdaten verzichtet, da ich nicht weiß, wie einverstanden sie damit wären, dass es in einem öffentlichen Repository steht.

Zu Bochum habe ich leider keine Links o.ä nur die kleine Demo

2023-06-21 08:56 UTC, malt-r requested changes

2023-06-21 08:56 UTC, malt-r commented on doc/related_work/partner.md
> +*   Kurzbeschreibung deren Projekt:
```suggestion
*   Kurzbeschreibung des Projekts: 
```

2023-06-21 08:56 UTC, malt-r commented on doc/related_work/partner.md
> +    *   Grafisches aufbereiten der Aufgaben im Moodle
```suggestion
    *   Grafisches Aufbereiten der Aufgaben im Moodle
```

2023-06-21 08:56 UTC, malt-r commented on doc/related_work/partner.md
> +    *   Klinken sich per JavaScript in Moodle ein.
```suggestion
    *   Klinken sich per JavaScript in Moodle ein
```

2023-06-21 11:46 UTC, cagix requested changes
rücke mal bitte den text aus der email einmal ein, dann gehört es logisch unter den zweiten stichpunkt.

und mache aus den "verweisen" einfach eine fußnote: im text ein `[^1]` und am ende dann ein `[^1]: blablabla` (eine pro zeile).

2023-06-21 11:46 UTC, cagix commented on doc/related_work/partner.md
> +> Ich bin wissenschaftlicher Mitarbeiter am Hasso-Plattner-Institut an der Universität Potsdam und beschäftige mich im Rahmen meiner Promotion mit Fragestellungen zur Programmierausbildung mittels Ma
```suggestion
> Ich bin wissenschaftlicher Mitarbeiter am Hasso-Plattner-Institut an der Universität Potsdam und beschäftige mich im Rahmen meiner Promotion mit Fragestellungen zur Programmierausbildung mittels Massive Open Online Courses (MOOCs). Dazu bieten wir in Online-Kursen auf openHPI [^1] für verschiedene Programmiersprachen (darunter Java, Python, Ruby, und R) praktische Programmieraufgaben an, die Lernende direkt im Browser in unserer Plattform CodeOcean [2] lösen können. In CodeOcean sind dazu zu den Aufgaben verschiedene Tests hinterlegt (etwa mit JUnit oder PyUnit für Unit-Tests oder PyLint für statische Codeanalyse), deren Ergebnisse den Lernenden während der Bearbeitung angezeigt werden. Bei weitergehenden Fragen haben wir einen Peer-Feedback-Mechanismus etabliert, mit dem sich Lernende gegenseitig unterstützen können.
```

2023-06-21 11:46 UTC, cagix commented on doc/related_work/partner.md
> +> [1]: https://open.hpi.de/
```suggestion
[1]: https://open.hpi.de/
```

2023-06-21 11:46 UTC, cagix commented on doc/related_work/partner.md
> +Projektbeschreibung (per E-Mail erhalten):
```suggestion
*   Projektbeschreibung (per E-Mail erhalten):  
```

2023-06-21 11:46 UTC, cagix commented on doc/related_work/partner.md
> +> Ich bin wissenschaftlicher Mitarbeiter am Hasso-Plattner-Institut an der Universität Potsdam und beschäftige mich im Rahmen meiner Promotion mit Fragestellungen zur Programmierausbildung mittels Ma
```suggestion
    > Ich bin wissenschaftlicher Mitarbeiter am Hasso-Plattner-Institut an der Universität Potsdam und beschäftige mich im Rahmen meiner Promotion mit Fragestellungen zur Programmierausbildung mittels Massive Open Online Courses (MOOCs). Dazu bieten wir in Online-Kursen auf openHPI [1] für verschiedene Programmiersprachen (darunter Java, Python, Ruby, und R) praktische Programmieraufgaben an, die Lernende direkt im Browser in unserer Plattform CodeOcean [2] lösen können. In CodeOcean sind dazu zu den Aufgaben verschiedene Tests hinterlegt (etwa mit JUnit oder PyUnit für Unit-Tests oder PyLint für statische Codeanalyse), deren Ergebnisse den Lernenden während der Bearbeitung angezeigt werden. Bei weitergehenden Fragen haben wir einen Peer-Feedback-Mechanismus etabliert, mit dem sich Lernende gegenseitig unterstützen können.
```

2023-06-21 11:47 UTC, cagix commented on doc/related_work/partner.md
> +    *   Nutzen das Moodle Feedbacksystem um Hinweise zu geben
Kannst Du sagen, um was für Aufgaben es hier geht und was die mit dem einklinkenden Javascript genau machen?

2023-06-23 07:07 UTC, AMatutat commented on doc/related_work/partner.md
> +> Ich bin wissenschaftlicher Mitarbeiter am Hasso-Plattner-Institut an der Universität Potsdam und beschäftige mich im Rahmen meiner Promotion mit Fragestellungen zur Programmierausbildung mittels Ma
manuell eingetrage

2023-06-23 07:08 UTC, AMatutat commented on doc/related_work/partner.md
> +    *   Nutzen das Moodle Feedbacksystem um Hinweise zu geben
so gut wie möglich verfeinert

2023-06-23 07:11 UTC, AMatutat commented
@cagix GitHub spielt wieder etwas versteckspiel mit den Conversations, daher hoffe ich mal nix übersehen zu haben

2023-06-23 07:11 UTC, cagix approved these changes

2023-06-23 12:26 UTC, merged