[GAME] implement basic structure for Tasks
Programmiermethoden/Dungeon pull request #826
Opened 2023-07-06 14:05 UTC by AMatutat

Bitte hier ist die korrigierte Version:

"Implementiert das in #806 diskutierte Konstrukt für die Darstellung von Aufgaben (Tasks) im Spiel.

Dieser PR setzt lediglich das Konstrukt um und wendet es noch nicht auf konkrete Aufgabentypen an (z. B. Quizfragen). Das wird in separaten PRs geschehen.

Die Klassen-Javadoc ist an einigen Stellen noch etwas vage formuliert, da einige Konzepte für mich noch nicht zu 100% greifbar sind (z. B. `TaskContent`).
Ich denke, vieles wird sich bei der aktiven Verwendung klären, und dann kann die Javadoc entsprechend angepasst werden.
Aber sie bildet bereits eine gute Grundlage, um große konzeptionelle Fragen/Unstimmigkeiten zu identifizieren."

2023-07-07 06:42 UTC, cagix reviewed
@AMatutat so far just basic boiler plate, oder?


ein paar gedanken:

- sollte die "taskmanagercomponent" nicht einfach "taskcomponent" heissen? dann wäre es symmetrisch zu den anderen components.
- ich bin mir immer noch nicht sicher, ob ich als entität nicht nur den task brauche? wenn ich den task sowieso habe, komme ich darüber doch auch an alle taskcontent-elemente. 
- ich bin mir immer noch nicht sicher, ob ich als taskcontent wirklich wissen muss, welchem task ich zugeordnet bin? das erinnert mich immer an den "drang", bei der modellierung von bäumen alles bidirektional zu formulieren, obwohl eine richtung völlig ausreicht.
- task hat ne ganze menge konstruktoren. scheinbar ist auch ein task erlaubt, der einfach nur einen defaultnamen hat. gleichzeitig gibt es setter für alle attribute. ich würde mich für eine der beiden varianten entscheiden: entweder setter und dann nur den default-ctor, oder nur die vielen ctor'en. oder vielleicht noch besser hier dann wirklich mal auf das builder-pattern umsteigen?
- wie werden wir mit dem petri-netz arbeiten? ist das eine aktive komponente, d.h. steuert die selbst was, oder ist das nur eine art verwaltung von zuständen und wird irgendwie (wie?) von außen benutzt?
- der code für die quest wird jetzt gelöscht. eine quest ist nach meinem verständnis eine sammlung von tasks - was wir irgendwie jetzt mit einem petri-netz formulieren. aber müssen wir nicht nach außen trotzdem irgendwie quests repräsentieren oder sind das dann einfach instanzen von petrinet?

2023-07-07 08:12 UTC, AMatutat commented
> @AMatutat so far just basic boiler plate, oder?

yep

> ein paar gedanken:
> 
> * sollte die "taskmanagercomponent" nicht einfach "taskcomponent" heissen? dann wäre es symmetrisch zu den anderen components.

FInd ich gut, bin mir aber nicht sicher, ob man das dann nicht als "Die Entität ist die Task" lesen würde... 

> * ich bin mir immer noch nicht sicher, ob ich als entität nicht nur den task brauche? wenn ich den task sowieso habe, komme ich darüber doch auch an alle taskcontent-elemente.

Die Manager-Entität braucht aus meiner Sicht nur den Task. Das TaskContentComponent macht eine Entität zu einem TaskContent, muss also wissen zu was für einen. 

> * ich bin mir immer noch nicht sicher, ob ich als taskcontent wirklich wissen muss, welchem task ich zugeordnet bin? das erinnert mich immer an den "drang", bei der modellierung von bäumen alles bidirektional zu formulieren, obwohl eine richtung völlig ausreicht.

@malt-r das kannst du vermutlich besser beantworten, aber in meinen Verständnis müssen für von der Entität mit dem TaskContentComponent irgendwie auf den Task kommen. Und da ist der Weg "Entität -> TaskContentComponent -> TaskContent -> Task" 



> * task hat ne ganze menge konstruktoren. scheinbar ist auch ein task erlaubt, der einfach nur einen defaultnamen hat. gleichzeitig gibt es setter für alle attribute. ich würde mich für eine der beiden varianten entscheiden: entweder setter und dann nur den default-ctor, oder nur die vielen ctor'en. oder vielleicht noch besser hier dann wirklich mal auf das builder-pattern umsteigen?

Über das builder-pattern habe ich auch nachgedacht, hab es dann aber verworfen weil ich für das bulden einer Task die TaskContents brauche, um TaskContents zu bauen brauch ich aber einen Task. Das ist der eklige Nachteile an der "doppel" Verkettung. 
Ansonsten wollte ich mit der Menge der Konstruktoren erstmal jeden möglichen Fall abdecken. Vermutlich ist da ein wenig YAGNI drinne, ich kann aktuell nur nicht sagen wo und für das parallele arbeiten wollte ich dann zumindest eine "feste" Grundstruktur setzen, mit der jeder arbeiten kann. 


> * wie werden wir mit dem petri-netz arbeiten? ist das eine aktive komponente, d.h. steuert die selbst was, oder ist das nur eine art verwaltung von zuständen und wird irgendwie (wie?) von außen benutzt?

Konkret ist die Frage noch nicht beantwortet, oder @malt-r ? Das Petri-Netz soll am Ende schon **das** Steuerende Element sein. Wie genau das in der Implementierung aussieht... who knows

> * der code für die quest wird jetzt gelöscht. eine quest ist nach meinem verständnis eine sammlung von tasks - was wir irgendwie jetzt mit einem petri-netz formulieren. aber müssen wir nicht nach außen trotzdem irgendwie quests repräsentieren oder sind das dann einfach instanzen von petrinet?

Eine Quest ist für mich eine Task incl. den ganzen TaskContent und Entitäten.
Eine Quest könnte dann eine einfache Task sein, oder ein Petri-Netz, was dann eine Sammlung an Tasks wäre. 

Also  das: 

> sind das dann einfach instanzen von petrinet

2023-07-07 09:17 UTC, cagix commented
> > * sollte die "taskmanagercomponent" nicht einfach "taskcomponent" heissen? dann wäre es symmetrisch zu den anderen components.
> 
> FInd ich gut, bin mir aber nicht sicher, ob man das dann nicht als "Die Entität ist die Task" lesen würde...

wäre potentiell das wohl möglich. andererseits lese ich ja auch die "velocitycomponent" nicht als "ich als entität bin die geschwindigkeit", sondern "ich als entität habe eine geschwindigkeit". dito mit dem task: "ich als entität habe einen task".


> > * ich bin mir immer noch nicht sicher, ob ich als entität nicht nur den task brauche? wenn ich den task sowieso habe, komme ich darüber doch auch an alle taskcontent-elemente.
> 
> Die Manager-Entität braucht aus meiner Sicht nur den Task. Das TaskContentComponent macht eine Entität zu einem TaskContent, muss also wissen zu was für einen.

stimmt. die entitäten können taskcontent sein. das ist im prinzip wie bei den items, oder? items sind entitäten mit itemcontent. könnte man die modellierung hier direkt übernehmen/anpassen?


> > * task hat ne ganze menge konstruktoren. scheinbar ist auch ein task erlaubt, der einfach nur einen defaultnamen hat. gleichzeitig gibt es setter für alle attribute. ich würde mich für eine der beiden varianten entscheiden: entweder setter und dann nur den default-ctor, oder nur die vielen ctor'en. oder vielleicht noch besser hier dann wirklich mal auf das builder-pattern umsteigen?
> 
> Über das builder-pattern habe ich auch nachgedacht, hab es dann aber verworfen weil ich für das bulden einer Task die TaskContents brauche, um TaskContents zu bauen brauch ich aber einen Task. Das ist der eklige Nachteile an der "doppel" Verkettung. Ansonsten wollte ich mit der Menge der Konstruktoren erstmal jeden möglichen Fall abdecken. Vermutlich ist da ein wenig YAGNI drinne, ich kann aktuell nur nicht sagen wo und für das parallele arbeiten wollte ich dann zumindest eine "feste" Grundstruktur setzen, mit der jeder arbeiten kann.

gerade mit dem yagni-gedanken hätte ich den basiscode eher so schlank wie möglich gehalten und nur _eine_ minimal-variante angeboten. wer dann später wirklich mehr oder was anderes braucht, kann das ja per pullrequest einkippen. 

mit dem grad eingeschlagenen weg müssen wir später dann nochmal aufräumen.



> 
> > * wie werden wir mit dem petri-netz arbeiten? ist das eine aktive komponente, d.h. steuert die selbst was, oder ist das nur eine art verwaltung von zuständen und wird irgendwie (wie?) von außen benutzt?
> 
> Konkret ist die Frage noch nicht beantwortet, oder @malt-r ? Das Petri-Netz soll am Ende schon **das** Steuerende Element sein. Wie genau das in der Implementierung aussieht... who knows

das ist aber eine der zentralen fragen :) auf dem papier ist die arbeitsweise ja klar, aber hier in der implementierung hängen davon eine ganze menge design-entscheidungen ab (siehe mein kommentar zur quest).

@Amtatutat @malt-r bitte versucht, diese frage möglichst bald zu klären.

2023-07-07 12:12 UTC, malt-r commented
> > > * ich bin mir immer noch nicht sicher, ob ich als entität nicht nur den task brauche? wenn ich den task sowieso habe, komme ich darüber doch auch an alle taskcontent-elemente.
> > 
> > @malt-r das kannst du vermutlich besser beantworten, aber in meinen Verständnis müssen wir von der Entität mit dem TaskContentComponent irgendwie auf den Task kommen. Und da ist der Weg "Entität -> TaskContentComponent -> TaskContent -> Task"
> >
> > Die Manager-Entität braucht aus meiner Sicht nur den Task. Das TaskContentComponent macht eine Entität zu einem TaskContent, muss also wissen zu was für einen.
> 
> stimmt. die entitäten können taskcontent sein. das ist im prinzip wie bei den items, oder? items sind entitäten mit itemcontent. könnte man die modellierung hier direkt übernehmen/anpassen?

Kern dieser ganzen Überlegung ist nicht, dass ich über die Entität herausbekommen will, welche Task damit verknüpft ist, sondern welcher TaskContent genau (also Antwortmöglichkeit, Crafting-Zutat, etc.) durch die Entität repräsentiert wird. Das erfordert eine 1:1 Zuordnung zwischen Entität und TaskContent, da wir sonst bei der Bewertung keine Möglichkeit haben, von einer konkreten Entität zurückzuschließen, welche konkrete Antwortmöglichkeit durch die Entität repräsentiert wird.

> * ich bin mir immer noch nicht sicher, ob ich als taskcontent wirklich wissen muss, welchem task ich zugeordnet bin? das erinnert mich immer an den "drang", bei der modellierung von bäumen alles bidirektional zu formulieren, obwohl eine richtung völlig ausreicht.

Die Sache ist, dass sich von Szenario zu Szenario unterscheiden kann, von welcher "Richtung" wir aus der Bewertungsfunktion an den Task und TaskContent kommen (für die Bewertung brauchen wir beides). Beide Szenarien/Richtungen sind [hier](https://github.com/Programmiermethoden/Dungeon/issues/610#issuecomment-1606913716) eigentlich beschrieben, ich finde die Beschreibung allerdings grade nicht in der Doku in #806, das muss dann wahrscheinlich noch ergänzt werden. 

In kurz - wir haben in einer Eventhandler-Funktion, welche die Bewertung anstößt:
1. direkten Zugriff auf eine Entität, welche eine Antwortmöglichkeit repräsentiert (und somit auf den TaskContent) und brauchen noch den Task.
2. direkten Zugriff auf die TaskManager-Entität (z.B. den Zauberer, von dem wir die Aufgabe bekommen haben) und somit die Task und brauchen noch Zugriff auf TaskContents.

Dass wir uns diese Flexibilität durch die bidirektionale Referenz zwischen Task und TaskContent erkaufen, klingt für mich nach einem guten Deal, weil wir uns damit auch Freiheit für die Gestaltung von Szenarien lassen.

2023-07-07 12:18 UTC, malt-r commented
> > > * wie werden wir mit dem petri-netz arbeiten? ist das eine aktive komponente, d.h. steuert die selbst was, oder ist das nur eine art verwaltung von zuständen und wird irgendwie (wie?) von außen benutzt?
> > 
> > 
> > Konkret ist die Frage noch nicht beantwortet, oder @malt-r ? Das Petri-Netz soll am Ende schon **das** Steuerende Element sein. Wie genau das in der Implementierung aussieht... who knows
> 
> das ist aber eine der zentralen fragen :) auf dem papier ist die arbeitsweise ja klar, aber hier in der implementierung hängen davon eine ganze menge design-entscheidungen ab (siehe mein kommentar zur quest). außerdem: wenn das petri-netz _die_ steuernde instanz ist: wie gehe ich damit um, wenn ich mehrere petri-netze habe, weil es mehrere quests und so gibt?
> 
> @Amtatutat @malt-r bitte versucht, diese frage möglichst bald zu klären.

Klären wir in #708

2023-07-07 12:26 UTC, malt-r requested changes

2023-07-07 12:36 UTC, AMatutat commented
> stimmt. die entitäten können taskcontent sein. das ist im prinzip wie bei den items, oder? items sind entitäten mit itemcontent. könnte man die modellierung hier direkt übernehmen/anpassen?


Im Grunde entspricht das der Modelierung (außer ich übersehe etwas).
`ItemComponent` speichert `ItemData` (bald heißt es nur noch `Item`), was es als Item markiert.
`TaskContentComponent` speichert `TaskContent` was es als Teil der Aufgabe markiert.

2023-07-07 12:38 UTC, AMatutat commented
Ich nehme mal als Todo mit
- [ ] `TaskManagmentComponent` -> `TaskComponent` 
- [ ] `Task` Konstruktoren nach YAGNI 
- [ ] Konzept in #806 nach Maltes anmerkung anpassen
- [ ] Code Suggestion


Fehlt euch etwas?

2023-07-10 08:05 UTC, AMatutat commented
Betreffend der `Task`-Konstruktoren:

Ich habe jetzt nur noch den leeren Konstruktor beibehalten. Ein `Task` wird jetzt (Builder Pattern Light) leer erzeugt und anschließend mithilfe der Setter konfiguriert.

Warum nicht direkt das Builder-Pattern verwenden? Ein `Task` benötigt zum einen ein `TaskComponent` und zum anderen eine Sammlung von `TaskContent`-Objekten. Beide Typen benötigen wiederum ein "Task"-Objekt, mit dem sie verknüpft sind.

Kurz gesagt: Ich kann keinen `Task` ohne `TaskContent` erstellen und keinen `TaskContent` ohne `Task`. Beim Builder-Pattern erhalte ich das `Task`-Objekt jedoch erst ganz am Ende.

Die "doppelte Verkettung" entsteht, weil wir situationsabhängig entweder vom Dungeon in die DSL telefonieren möchten (dann gehen wir über `Entity` -> `TaskContentComponent` -> `TaskContent` -> `Task`) oder von der DSL in das Dungeon (`Task` -> `TaskContent` -> `TaskContentComponent` -> `Entity`).

2023-07-11 15:41 UTC, malt-r submitted a review, later dismissed
Nach den Änderungen: lgtm

2023-07-11 16:07 UTC, cagix submitted a review, later dismissed
nur kurz vom handy: code und javadoc könnten so gehen als erster draft. insofern "approved".

aber: wenn du mich fragst, wirkt es auf mich immer noch wie ein überfrachteter rahmen, der möglichst alle eventualitäten abdecken soll, ohne diese zu kennen. einiges ist immer noch ziemlich "bloated" mit vielen gettern/settern, ohne dass mir klar ist, ob wir die wirklich so brauchen werden. die taskcontentcomponent hat z.b. alle nur denkbaren varianten für den ctor und dazu noch getter/setter für die taskcontent-objekte. was davon braucht man im einsatz später? wird man wirklich nachträglich taskcontent-objekte einer bestehenden component hinzufügen/wegnehmen oder wird man die nicht eher vollständig aufbauen und dann irgendwo reinsetzen?

und es ist uneinheitlich: mal haben wir allmächtige ctoren, mal einen minimal-ctor für plus getter/setter und mal beides. 

mein ansatz wäre, erstmal nur die klassen mit einer minimalen api reinzuwerfen und das dann schrittweise zu erweitern, sobald der bedarf klar ist :)

2023-07-11 19:16 UTC, AMatutat commented
Bin nochmal drüber gegangen und habe ein paar Methoden rausgeworfen. 
Für alle jetzt noch existierenden Methoden habe ich direkte Anwendungsfälle im Kopf die ich brauche. 


> und es ist uneinheitlich: mal haben wir allmächtige ctoren, mal einen minimal-ctor für plus getter/setter und mal beides.

Ja. Das zieht sich irgendwie durch das ganze Projekt. Daher #850

2023-07-11 19:31 UTC, cagix approved these changes

2023-07-11 19:35 UTC, merged