[DSL] Alle Datentypen im TypeBuilder in den globalen Scope einhängen
Programmiermethoden/Dungeon pull request #897
Opened 2023-07-24 15:20 UTC by malt-r

Übergibt die globale `Scope`-Instanz eines `Environments` an den Aufruf von `createDSLTypeForJavaTypeInScope`.
Der `TypeBuilder` erzeugt während der Erstellung des DSL-Datentyps für den übergebenen `Type` ggfs. noch andere Datentypen (z.B. `FunctionType`s für Callback-Methoden oder `ListType` und `SetType`s) as needed. Werden diese Datentypen nicht zentral im globalen `Scope` des verwendeten `Environments` gespeichert, kommt es zu duplizierten Datentypen. Daher muss der `TypeBuilder` während der Typerzeugung prüfen, ob die benötigten Datentypen evtl. schon vorhanden sind.

2023-07-24 17:10 UTC, AMatutat approved these changes

2023-07-24 17:13 UTC, AMatutat requested changes
hatte nicht auf die tests geachtet.....

2023-07-24 18:35 UTC, malt-r commented
Ich hab lokal mal eine master-Kopie und den Branch hier zusammengemerged und dabei laufen auch alle Tests durch.

2023-07-24 18:42 UTC, malt-r commented
@AMatutat kannst du mal bei dir `gradle test` ausführen und gucken, was passiert?

2023-07-24 19:21 UTC, AMatutat commented
> @AMatutat kannst du mal bei dir `gradle test` ausführen und gucken, was passiert?

laufen alle durch. (Mac OS)

2023-07-24 20:28 UTC, cagix commented
hmmm?

2023-07-25 14:13 UTC, AMatutat approved these changes
nach absprache und fix lgtm

2023-07-25 15:01 UTC, merged