[GAME] ProtectOnAttack `peek` vs `filter` überarbeitet
Programmiermethoden/Dungeon pull request #920
Opened 2023-08-02 08:39 UTC by JudiTeller

closes #751

In diesem PR wird die Nutzung eines peek durch einen übersichtlicheren Filterablauf ersetzt

2023-08-03 08:47 UTC, AMatutat requested changes
Irgendwie stört mich, dass zweimal über die Entitäten itteriert wird.

Vielleicht denken wir mit den Streams grade auch einfach zu komplex: 

In Pseudo java 
Classic For-Each? 
```java
List <Entity> toAdd;
for (Entity e: entities) 
e.isPresent(HealthComponent.class) toAdd.add(e)
else throw Exception
```

2023-08-09 09:32 UTC, AMatutat approved these changes
irgendwie find ich das deutlich schöner, danke ^^

2023-08-09 09:34 UTC, JudiTeller commented
@AMatutat Habs noch mal, wie von dir vorgeschlagen in Einzeiler geschrieben, müsstest noch mal approven ^^

2023-08-09 09:54 UTC, AMatutat approved these changes
sexy

2023-08-09 09:55 UTC, merged