[GAME] store Entities in the level
Programmiermethoden/Dungeon pull request #942
Opened 2023-08-09 15:02 UTC by AMatutat

fixes #900 

- Fügt in der Klasse `Game` die `Map<ILevel, Set<EntityStorageMapper>>` hinzu. 
- Die Map stellt die Verbindung zwischen den Leveln und den Entitäten her.
- Der aktive Storage ist das `Set<EntityStorageMapper>` des aktiven Levels.
- Im `Game#onLevelLoad` werden jetzt alle Systeme aus dem "alten" `Set<EntityStorageMapper>` entfernt. Dadurch werden alle `System#onEntityRemove`-Methoden ausgelöst, ohne die Entitäten tatsächlich zu löschen (denn diese werden beim Neuladen des Levels noch benötigt).
- Für das neue Level werden die Systeme anschließend wieder hinzugefügt, was jeweils jedes `System#onEntityAdd` auslöst.
- `userOnLevelLoad` ist nun ein `Consumer<Boolean>`. Der Boolean gibt an, ob das Level schon einmal geladen wurde. Dadurch können Monster und Schatzkisten nur beim ersten Mal hinzugefügt werden.

2023-08-09 21:56 UTC, fwatermann approved these changes
LGTM

2023-08-10 09:57 UTC, malt-r requested changes

2023-08-10 09:57 UTC, malt-r commented on dungeon/test/manual/dslFileReader/DslFileReaderTest.java
> +                b -> {
Hier würde ich mir eine aussagekräftigere Bezeichung von `b` wünschen, weil ich nur, wenn ich das hier sehe, keine Ahnung habe, was das aussagen soll (wirkt etwas magisch).

2023-08-10 09:57 UTC, malt-r commented on dungeon/test/manual/quizquestion/CallbackTest.java
> +                (b) -> {
Dito

2023-08-10 09:57 UTC, malt-r commented on dungeon/test/manual/taskgeneration/TaskGenerationTest.java
> +                (b) -> {
Dito

2023-08-11 09:50 UTC, malt-r approved these changes

2023-08-11 11:03 UTC, AMatutat commented
@fwatermann frag mich nicht warum ich dein review nochmal brauch....

2023-08-23 10:26 UTC, Lena241 approved these changes
lgtm

2023-08-23 10:36 UTC, merged