[GAME] add Graohen-Level
Programmiermethoden/Dungeon pull request #956
Opened 2023-08-18 12:25 UTC by AMatutat

fixes #113, fixes #607. fixes #608,  fixes #902

Anmerkung: Dieser PR/Branch dient als Haupt-Branch, um den Levelgenerator schrittweise fertigzustellen. Ich werde Feature-Branches von diesem Haupt-Branch aus erstellen und in diesen hier integrieren. Dadurch kann ich strukturiert arbeiten, ohne auf Reviews warten zu müssen, um in den Haupt-Branch zu mergen. Außerdem erspare ich mir das mühsame Neubasieren nach einem "Squash Merge".

## Zu #113

- Entfernt alte Überbleibsel des PoC-Generators.
- Fügt einen Levelgraphen-Generator hinzu:
    - Der Generator erzeugt zunächst einen Baum und fügt dann zufällige Kanten hinzu, um aus dem Baum einen unterhaltsameren Graphen zu machen.
    - Die Anzahl der Knoten im Graphen wird durch die Anzahl der `Set<Entity>` bestimmt.
    - Knoten speichern die Entity-Collections als Payload.
    - Knoten haben maximal vier Nachbarn und werden richtungsbasiert verbunden (dieses Spiel bedeutet, dass von A über links nach B geht und von B über rechts nach A).
    
- Aktuell gibt es noch einen Bug, durch den es manchmal vorkommt, dass ein Knoten nicht mit dem Graphen verbunden ist.

## Zu #607
Aktuell erstellt der Raumgenerator direkt `ILevel` Instanzen. Für die Überarbeitung wird dieser auf die Generierung von Layouts (`Tile[][]`) runtergebrochen. 
Die Layouts lassen sich später über die Konstruktoren von `TileLevel` Problemlos zu einem Level Parsen.
Der Vorhandene Code ist sehr fragil und ich will diesen daher eigentlich am liebsten vollständig neu schreiben und nur Ideen recyceln. 

## Zu #608
Jetzt geht es darum den Raumgenerator und den Graphen zu verbinden und daraus Level im Spiel zu machen.

- Für jeden Knoten im Graphen ein Raum-Layout (`Tile[][]`) erzeugen
     - Layouts warden als zusätzliche PayLoad im Node gespeichert
- Die Layouts können dann zu `TileLevel´ gemacht werden 
- Door-Tiles hinzufügen und die logische Verbindung erstellen (onEnter->loadNexteLevel) 
- Die Entitäten müssen dann hinzugefügt werden (vermutlich muss dafür einmal jeder Raum im `Game` als aktives Level gesetzt werden)

2023-08-18 13:21 UTC, cagix commented
@AMatutat und wer soll dann am ende diesen riesigen big-bang-pr reviewen? außerdem steigt das risiko von merge-konflikten deutlich an für so lang laufende pr's... 

ich kann die motivation hinter diesem pr verstehen, aber mir kommt das grad so vor, als ob wir damit absichtlich alle bisher gemachten erfahrungen ignorieren.

die referenzierten tickets wirken auf mich, als ob man die wirklich gut nacheinander bearbeiten und einzeln mergen kann.

2023-08-18 14:31 UTC, AMatutat commented
> @AMatutat und wer soll dann am ende diesen riesigen big-bang-pr reviewen? außerdem steigt das risiko von merge-konflikten deutlich an für so lang laufende pr's...

Ich lass mir die Pull-Requests die in diesen Branch reingehen werden reviewn. Für den Merge in den master braucht es dann nur noch ein obligatorisches review, da alle Teilpakete reviewed wurden. 

So drüber nachgedacht, sollte ich mir eigentlich nochmal einen cleanen Feature-Branch aus dem Master holen, diesen (und alle folgenden PRs) auf den Branch umleiten, so stell ich die Struktur auch für die bereits gemachten Commits her... Ich glaub das mach ich.


> die referenzierten tickets wirken auf mich, als ob man die wirklich gut nacheinander bearbeiten und einzeln mergen kann.

Kann man eigentlich auch, deswegen sind sie auch entsprechend angelegt. Das Problem ist, das ich entweder darauf warten muss bis mir hier jemand ein Review gibt oder das squash-merge rebase problem holt mich ein

> edit: das mit dem "mühsamen rebase wg. squash-merge" höre ich nicht zum ersten mal, aber verstanden habe ich das noch nicht. eli5: was genau ist das problem dabei?

Die Squash-Merge rebase Probleme treten meiner Erfahrung nur dann auf, wenn man aus einen Feature Branch (A) (welcher direkt aus dem Master kommt) einen weiteren Feature Branch (B) anlegt.

Der PR von Branch A in den Master sieht z.B so aus 
- commit A.1
- commit A.2
- commit A.3

Der PR von Branch B in den Master sieht z.B so aus
- commit A.1
- commit A.2
- commit A.3
- commit B.1
- commit B.2

Wenn jetzt der Branch A in den Master gesquash mergt wird, kann Git(hub) keine Verbindung zwischen den Commit der beiden Branches/PRs ziehen. 

Eigentlich würde man erwaten/wollen das der PR B nach den Merge von A nur noch: 
- commit B.1
- commit B.2

enthält.

In der Praxis sieht er aber weiterhin so aus:
- commit A.1
- commit A.2
- commit A.3
- commit B.1
- commit B.2


Für Git(hub) sind die Commits A.1-A.3 neu und sorgen für merge-konflikte mit dem master. Da spielt es auch keine Rolle ob es faktisch keine unterschiede auf der Codebase gibt. 

Was du jetzt machen müsstest ist, jeweils für jeden Commit A.1, A.2 und A.3 beim rebasen die Merge-Konflikte beheben, dabei programmierst du quasi den gesamten PR A nach. Grade wenn wir von teilweise 10+ Commits reden ist das echt aufwendig/nervig und zusätzlich sehr frustrierend, da es ja eigentlich keine Änderungen gibt. 

Ich hab teilweise schon angefangen beim rebasen einfach den Code aus dem Master 1zu1 zu kopieren.... Aber wirklich schon, schnell oder spaßig ist das auch nicht.



Ich hoffe das war Halbwegs verständlich, das zu erklären fällt mir schwer. Gehört in die Kategorie: Muss man erlebt haben.

2023-08-18 15:01 UTC, cagix commented
> Ich lass mir die Pull-Requests die in diesen Branch reingehen werden reviewn. Für den Merge in den master braucht es dann nur noch ein obligatorisches review, da alle Teilpakete reviewed wurden.

Das klang in Deinem ursprünglichen Kommentar aber noch anders: "Dadurch kann ich strukturiert arbeiten, ohne auf Reviews warten zu müssen, um in den Haupt-Branch zu mergen."

Und ich würde trotz der Teilreviews stark dazu raten, den Gesamt-PR auch angemessen zu reviewen (also mehr als nur das obligatorische "lgtm"). Hier sieht man ja erst das Zusammenspiel der einzelnen Sachen ...

> Die Squash-Merge rebase Probleme treten meiner Erfahrung nur dann auf, wenn man aus einen Feature Branch (A) (welcher direkt aus dem Master kommt) einen weiteren Feature Branch (B) anlegt.

Hmmm. Das ist eigentlich eine schlechte Praxis und sollte gar nicht vorkommen ;) 

Du suchst nach `git rebase --onto`. Damit kannst Du einen "Pivot-Commit" benennen, ab dem rebased werden soll. In Deinem Beispiel wäre das B.1: `git rebase --onto master B.1 feature-b`.

2023-08-23 13:18 UTC, Lena241 requested changes

2023-08-23 13:18 UTC, Lena241 commented on game/src/core/level/generator/graphBased/graph/LevelGraph.java
> +            // select atAt connection direction
```suggestion
            // select addAt connection direction
```

2023-08-23 13:18 UTC, Lena241 commented on game/src/core/level/generator/graphBased/graph/LevelGraph.java
> +                    // add this node to the neighbour at the atAt direction of this node
```suggestion
                    // add this node to the neighbour at the addAt direction of this node
```

2023-08-24 07:18 UTC, merged