[DUNGEON] implement basic Petri Net structure
Programmiermethoden/Dungeon pull request #993
Opened 2023-08-31 11:31 UTC by AMatutat

fixes #991 

- fügt die Klassen `Place` und `Transition` ein
- entfernt die Klasse `PetriNet`, da das Konzept "Ein Petri Netz ist selbst ein Task" nicht mehr up to date ist
- `Transition` observiert `Place` 
- Die Kanten des Petri Netz sind in den Sets von `Transition` integriert `dependencyPlaces` sind quasi alle Pfeile von einer Stelle in eine Transition und `addTokenOnFire` sind die Pfeile von einer Transition in eine Stelle

@malt-r Ich habe jetzt keinen Grund gehabt die Kanten als eigene Klasse umzusetzen, hast du einen? Gleiches gilt für eine Petri-Net` Klasse, die würde m.M aktuell eh nur ein Container für `Set<Transition>` und `Set<Place>` sein. 

Dieser PR bindet das ganze noch nicht an das Task konstrukt an. Das folgt noch 
Kurzer Ausblick: In `Transition#fire` würde dann für alle Places in `addTokenOnFire` der entsprechende Task rausgesucht werden und für den Task die entsprechende Tür, dann kann man die aufmachen.

2023-09-02 13:00 UTC, malt-r requested changes
> Ich habe jetzt keinen Grund gehabt die Kanten als eigene Klasse umzusetzen, hast du einen? 

Eigentlich kann für jede Kante festgelegt werden, wie viele Tokens sie aus einer Stelle entnimmt. Das wäre ein Grund. Für die Modellierung in [der Doku](https://github.com/Programmiermethoden/Dungeon/blob/master/doc/control_mechanisms/petri_nets.md) habe ich allerdings auch immer den einfachsten Fall mit Anzahl Tokens pro Kante = 1 angenommen. Von daher kann das von mir aus erstmal so bleiben.

> Gleiches gilt für eine Petri-Net Klasse, die würde m.M aktuell eh nur ein Container für Set<Transition> und Set<Place> sein.

Ein Grund wäre, es als abschlossene Einheit verwenden zu können und die Member unter einem Namen zusammen zu fassen. Wie sonst auch nach dem OOP-Gedanken.

2023-09-03 12:13 UTC, AMatutat commented on dungeon/src/petriNet/Transition.java
> +    }
Habs eingebaut.
Wenn eine Transition feuert, entfernt sie jetzt von allen Stellen ein Token.
Die Reduzierung des Token-Count wird dann auch den Tansitionen mitgeteilt (falls damit eine Transition auf 0 Token fällt)

2023-09-03 12:45 UTC, AMatutat commented
Ich hab mal fix ein möchtegern Sequenzdiagramm gebaut:

![Diagram 2023-09-03 14-40-49](https://github.com/Programmiermethoden/Dungeon/assets/32962412/f82da78e-2ce9-4e55-afbd-35a4ca843eab)


in aller kürze:

Zu beginn wird "von außen" ein Token in "Place: Task A aktiviert" gelegt, der `Place` setzt dann den Status des `Task A` auf `active`. Wenn ein `Task` auf `active` gesetzt wird, aktiviert der `Task` seine Manager-Entität (das ist #995), der `TaskManager` öffnet dann die Tür zum Task (falls nötig).

Irgendwann löst der Spieler die Aufgabe und der DSL-Callback wird ausgelöst. Dort findet dann die Bewertung statt und die DSL setzt "über" den EntityManager (vielleicht auch direkt) den Task auf `done`.

Der `Task A` legt dann ein Token in den `Place` "Place: Task A fertig".

Da sich sowohl in "Place: Task A aktiviert" und "Place: Task A fertig" ein Token befindet, feuert die Transition, entfernt also die Token aus den beiden Places und legt ein Token in den "Pace B: aktiviert". 
Der Place aktiviert dann den Task B usw...

2023-09-04 08:36 UTC, AMatutat commented
Nach Besprechung machen wir eine Kombination aus dem bereits implementieren und Vorschlag 2:

Grober Pseudocode 

```

public class Task
    - int tokenCount;
    - Map<Task,State> changeStateOnTokenAdd;
    - Map<Task,State> addTokenOn;


    boolean changeTaskStateOnTokenGet(Task changeStateFor, State state){
        if(addTokenOn!=empty) return false;
        changeStateOnTokenAdd.put(changeStateFor,State state);
    }

    boolean getTokenOnChange(Task taks, State state){
        if(changeStateOnTokenAdd!=empty) return false;
        task.register(this);
        addTokenOn.put(task,state);
    }

    void notify(Task task, State state){
        if(addTokenOn.get(task).equals==state)
            addToken();
    }

    void addToken(){
        tokenCount++;
        
        for each entry in changeStateOnTokenAdd set key.state(value);

    }

    void removeToken....




    public class Task

    void state(State state){
        //state kann sein active, inactive, finisehd.good, finished.bad, finished.naja
        this.sate=state;
        observer.forAll(Place::notify(this,state))

        if(state==active) -> EntityManager.fetch(TaskComponent.class).get().activate() //=> Tür öffnen
    
        }
    
```

2023-09-04 11:49 UTC, malt-r approved these changes

2023-09-04 12:17 UTC, merged